project:
  type: website
  output-dir: "_site"

website:
  title: "Anusha's_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
    df_print: paged

editor: visual

