---
title: "Testing-a-Single-Proportion"
author: "Anusha"
---

## CLT for Proportions

My metric is not a mean, it is a proportion.

```{r}
#| label: setup
library(tidyverse)
library(mosaic)
library(ggformula)
library(infer)

## Datasets from Chihara and Hesterberg's book (Second Edition)
library(resampledata)

## Datasets from Cetinkaya-Rundel and Hardin's book (First Edition)
library(openintro)
```

```{r}
data(yrbss, package = "openintro")
yrbss
```

```{r}
yrbss %>%
  group_by(helmet_12m) %>%
  count()
```

```{r}
##
yrbss %>%
  group_by(text_while_driving_30d) %>%
  count()
```

```{r}
no_helmet_text <- yrbss %>%
  filter(helmet_12m == "never") %>%
  mutate(text_ind = ifelse(text_while_driving_30d == "30", "yes", "no")) %>%
  # removing most of the other variables
  select(age, gender, text_ind)
no_helmet_text
```

```{r}
##
no_helmet_text %>%
  drop_na() %>%
  count(text_ind)
```

```{r}
##
no_helmet_text %>%
  drop_na() %>%
  summarize(prop = prop(text_ind, success = "yes"), n = n())
```

### Visualizing a single proportion

```{r}
# Set graph theme
#theme_set(new = theme_custom())
#
no_helmet_text %>%
  drop_na() %>%
  gf_bar(~text_ind) %>%
  gf_labs(
    x = "texted?",
    title = "High-Schoolers who texted every day",
    subtitle = "While driving with no helmet on!!"
  )
```

### **Hypothesis Testing for a Single Proportion**

Classical test: Simple test in R called binom.test

```{r}
mosaic::binom.test(~text_ind, data = no_helmet_text, success = "yes")
```

```{r}
mosaic::binom.test(~text_ind, data = no_helmet_text, success = "yes") %>%
  broom::tidy()
```

This is a good estimate for children who drive and text.

It consists of 7% of the population.

Bootstrap test:

```{r}
no_helmet_text %>%
  drop_na() %>%
  specify(response = text_ind, success = "yes") %>%
  generate(reps = 999, type = "bootstrap") %>%
  calculate(stat = "prop") %>%
  get_ci(level = 0.95)
```
