<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anusha">

<title>Pocket-Money – Anusha’s_Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../../site_libs/tabwid-1.1.3/tabwid.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Anusha’s_Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Pocket-Money</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Anusha </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="guys-have-more-pocket-money-than-gals." class="level1">
<h1><strong>Guys have more pocket money than Gals.</strong></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(crosstable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'crosstable'

The following object is masked from 'package:purrr':

    compact</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
</div>
<p>Let’s first import and read our data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>money <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../Data/PocketMoney.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 82 Columns: 5
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(2): Name, Gender dbl (2): Sr no, Money_spent lgl (1): ...5
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...5`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>money</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 82 × 5
   `Sr no` Name     Gender Money_spent ...5 
     &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt; &lt;lgl&gt;
 1       1 Aagam    Male           150 NA   
 2       2 Aakash   Male           240 NA   
 3       3 Aarushi  Female         382 NA   
 4       4 Abheeta  Female          60 NA   
 5       5 Adithya  Male            68 NA   
 6       6 Aditya   Male           300 NA   
 7       7 Akanksha Female         270 NA   
 8       8 Amruta   Female         190 NA   
 9       9 Anaaya   Female         300 NA   
10      10 Anish    Male             0 NA   
# ℹ 72 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(money)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
    name     class levels  n missing
1   Name character     82 82       0
2 Gender character      2 82       0
3   ...5   logical      0  0      82
                                   distribution
1 Aagam (1.2%), Aakash (1.2%) ...              
2 Female (50%), Male (50%)                     
3  (%)                                         

quantitative variables:  
         name   class min     Q1 median     Q3   max     mean         sd  n
1       Sr no numeric   1  21.25   41.5  61.75    82  41.5000   23.81526 82
2 Money_spent numeric   0 100.00  264.5 596.25 13000 720.9634 1835.72169 82
  missing
1       0
2       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(money)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 82
Columns: 5
$ `Sr no`     &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ Name        &lt;chr&gt; "Aagam", "Aakash", "Aarushi", "Abheeta", "Adithya", "Adity…
$ Gender      &lt;chr&gt; "Male", "Male", "Female", "Female", "Male", "Male", "Femal…
$ Money_spent &lt;dbl&gt; 150, 240, 382, 60, 68, 300, 270, 190, 300, 0, 250, 85, 700…
$ ...5        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
</div>
<section id="data-munging" class="level2">
<h2 class="anchored" data-anchor-id="data-munging">Data Munging</h2>
<p>Let us convert Gender as a factor since we perform calculations on this variable and because it has only 2 levels.</p>
<p>We are prepping our data for various test we are going to perform.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>money <span class="ot">&lt;-</span> money <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender =</span> <span class="fu">as_factor</span>(Gender)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(money)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 82
Columns: 5
$ `Sr no`     &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ Name        &lt;chr&gt; "Aagam", "Aakash", "Aarushi", "Abheeta", "Adithya", "Adity…
$ Gender      &lt;fct&gt; Male, Male, Female, Female, Male, Male, Female, Female, Fe…
$ Money_spent &lt;dbl&gt; 150, 240, 382, 60, 68, 300, 270, 190, 300, 0, 250, 85, 700…
$ ...5        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
</div>
</section>
<section id="what-is-our-null-hypothesis-for-this-data-set" class="level2">
<h2 class="anchored" data-anchor-id="what-is-our-null-hypothesis-for-this-data-set">What is our NULL Hypothesis for this data set?</h2>
<p><strong>“Guys carry more cash than Gals.”</strong></p>
<p>To test our hypothesis, we will perform a series of steps. This will lead us to a conclusion regarding what we have stated.</p>
<p>So, first we will find out the mean and standard deviation of money spent across the 2 genders.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>money <span class="sc">%&gt;%</span> <span class="fu">crosstable</span>(Money_spent<span class="sc">~</span>Gender) <span class="sc">%&gt;%</span> <span class="fu">as_flextable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-2f41dcc0{table-layout:auto;}.cl-2f3d961a{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f3d962e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f3f4316{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2f3f432a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2f3f563a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f3f563b{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f3f563c{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f3f5644{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f3f5645{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-2f41dcc0"><thead><tr style="overflow-wrap:break-word;"><th rowspan="2" class="cl-2f3f563a"><p class="cl-2f3f4316"><span class="cl-2f3d961a">label</span></p></th><th rowspan="2" class="cl-2f3f563a"><p class="cl-2f3f4316"><span class="cl-2f3d961a">variable</span></p></th><th colspan="2" class="cl-2f3f563b"><p class="cl-2f3f4316"><span class="cl-2f3d961a">Gender</span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-2f3f563c"><p class="cl-2f3f4316"><span class="cl-2f3d961a">Male</span></p></th><th class="cl-2f3f563c"><p class="cl-2f3f4316"><span class="cl-2f3d961a">Female</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td rowspan="4" class="cl-2f3f5644"><p class="cl-2f3f432a"><span class="cl-2f3d962e">Money_spent</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">Min / Max</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">0 / 1.0e+04</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">0 / 1.3e+04</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">Med [IQR]</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">250.0 [150.0;842.0]</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">280.0 [85.0;500.0]</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">Mean (std)</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">748.6 (1636.5)</span></p></td><td class="cl-2f3f5645"><p class="cl-2f3f432a"><span class="cl-2f3d962e">693.3 (2035.8)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f3f5644"><p class="cl-2f3f432a"><span class="cl-2f3d962e">N (NA)</span></p></td><td class="cl-2f3f5644"><p class="cl-2f3f432a"><span class="cl-2f3d962e">41 (0)</span></p></td><td class="cl-2f3f5644"><p class="cl-2f3f432a"><span class="cl-2f3d962e">41 (0)</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>The median spending is slightly higher for females compared to males. But, the means are relatively closer, with males averaging 748.6 and females 693.3. This indicates that while males might have a higher average spending, the central tendency (median) is slightly higher for females.</p>
<p>The high standard deviations for both genders suggest that spending varies widely within each group.</p>
<p>The data indicates that both genders have similar ranges of spending, but the higher average spending for males suggests they might be more likely to spend larger amounts compared to females.</p>
</section>
<section id="gender" class="level2">
<h2 class="anchored" data-anchor-id="gender">Gender</h2>
<section id="histogram" class="level3">
<h3 class="anchored" data-anchor-id="histogram">Histogram</h3>
<p>1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>Money_spent, <span class="at">fill =</span> <span class="sc">~</span>Gender, <span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">data =</span> money) <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#gf_facet_wrap(vars(Gender)) %&gt;% </span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title =</span> <span class="st">"Who gets more Pocket Money"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Seems like males have spent more money, which could probably indicate that they have more pocket money.</p>
<p>2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>money <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_density</span>(<span class="sc">~</span>Money_spent, <span class="at">fill =</span> <span class="sc">~</span>Gender, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">title =</span> <span class="st">"Who has more pocket money?"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(<span class="sc">~</span>Gender) <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_fitdistr</span>(<span class="at">dist =</span> <span class="st">"dnorm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Density plots provide a clear view of the distribution of a continuous variable.</p>
<p>By fitting a normal distribution, we can visually assess how closely the data resembles a normal distribution. This is useful when considering whether parametric tests like t-tests are appropriate for our data analysis.</p>
<p>Looking at this graph, we can assume that the distribution does not seem normal.</p>
</section>
</section>
<section id="check-for-normality" class="level2">
<h2 class="anchored" data-anchor-id="check-for-normality">Check for Normality</h2>
<p>First, let’s separate the two genders and call each group Female and Male, and then perform a normality test (shapiro test) for each of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>money <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">"Female"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Money_spent) <span class="ot">-&gt;</span> Female</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>Female</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 41 × 1
   Money_spent
         &lt;dbl&gt;
 1         382
 2          60
 3         270
 4         190
 5         300
 6          85
 7         700
 8         140
 9        1070
10        1200
# ℹ 31 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>money <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Money_spent) <span class="ot">-&gt;</span> Male</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>Male</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 41 × 1
   Money_spent
         &lt;dbl&gt;
 1         150
 2         240
 3          68
 4         300
 5           0
 6         250
 7        1143
 8         100
 9       10000
10        1433
# ℹ 31 more rows</code></pre>
</div>
</div>
<p>-&gt;Shapiro test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Female<span class="sc">$</span>Money_spent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Female$Money_spent
W = 0.29606, p-value = 8.961e-13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Male<span class="sc">$</span>Money_spent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Male$Money_spent
W = 0.40726, p-value = 1.136e-11</code></pre>
</div>
</div>
<p>In both cases, the p-values are extremely small, which indicates that we reject the null hypothesis. This means that the data for both females and males is not normal.</p>
<p>Now, let’s do a t-test (even though the distribution is not normal).</p>
<p>-&gt;t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">t_test</span>(Money_spent<span class="sc">~</span>Gender, <span class="at">data =</span> money) <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     55.3      749.      693.     0.136   0.893      76.5    -757.      868.
# ℹ 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
</div>
</div>
<p>The negative difference of −55.29 indicates that females spent slightly less on average compared to males.</p>
<p>The high p-value indicates that we do not have enough evidence to reject the null hypothesis. This suggests that the average amount of money spent between males and females is not significantly different.</p>
<p>Since, there is such uncertainty in the t-tests we should perform some other tests.</p>
<p>It is appropriate to conduct a Wilcox test for further analysis.</p>
<p>-&gt;Wilcox test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Money_spent<span class="sc">~</span>Gender, <span class="at">data =</span> money,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact confidence intervals with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  estimate statistic p.value conf.low conf.high method               alternative
     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                &lt;chr&gt;      
1     55.0      936.   0.381    -70.0      180. Wilcoxon rank sum t… two.sided  </code></pre>
</div>
</div>
<p>The negative estimate of −55 indicates that females tend to spend less than males on average, but this difference is not statistically significant.</p>
<p>The p-value suggests that, we fail to reject the null hypothesis.</p>
<p>So, now let us do the permutation test.</p>
<p>-&gt;Permutation test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>obs_mean <span class="ot">&lt;-</span> <span class="fu">diffmean</span>(Money_spent<span class="sc">~</span>Gender, <span class="at">data =</span> money)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>obs_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> diffmean 
-55.29268 </code></pre>
</div>
</div>
<p>As per previous calculations of the diff mean, here also we see that the difference of means is 55.2. But here it is positive as now we have calculated mean of Money spent(male) - mean of Money spent(female)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>null_dist_money <span class="ot">&lt;-</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>(<span class="dv">4999</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(<span class="at">data =</span> money, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                      Money_spent <span class="sc">~</span> <span class="fu">shuffle</span>(Gender))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>null_dist_money</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          diffmean
1     -18.12195122
2    -656.46341463
3     256.75609756
4     139.87804878
5    -603.87804878
6    -758.12195122
7    -142.07317073
8     184.51219512
9    -139.48780488
10    261.39024390
11   -279.09756098
12    798.46341463
13    649.09756098
14   -817.39024390
15   -305.68292683
16   -328.85365854
17   -467.92682927
18    179.92682927
19    -97.82926829
20    118.80487805
21   -543.43902439
22   -726.26829268
23    -76.70731707
24    354.85365854
25    204.70731707
26   -602.41463415
27   -545.78048780
28    594.46341463
29    720.85365854
30   -355.09756098
31    293.58536585
32    641.48780488
33    141.34146341
34    722.60975610
35   -142.02439024
36    -90.65853659
37   -585.09756098
38    -91.39024390
39    390.07317073
40   -172.36585366
41    340.90243902
42     53.68292683
43    273.48780488
44    -27.00000000
45     72.51219512
46    705.43902439
47   -216.12195122
48   -201.29268293
49   -839.82926829
50    501.92682927
51     60.70731707
52   -103.97560976
53     60.31707317
54     83.48780488
55   -355.39024390
56    155.68292683
57     73.73170732
58   -140.12195122
59    -21.48780488
60   -465.04878049
61    236.95121951
62    591.19512195
63    553.97560976
64   -101.14634146
65    -99.04878049
66   -214.95121951
67    423.82926829
68    -41.82926829
69    105.19512195
70    613.29268293
71    558.75609756
72     88.26829268
73    161.97560976
74    705.04878049
75   -475.19512195
76   -190.60975610
77    225.14634146
78   -236.60975610
79     41.78048780
80    613.92682927
81    695.24390244
82     69.00000000
83    582.12195122
84    -27.43902439
85    347.39024390
86     12.51219512
87   -189.58536585
88   -339.73170732
89   -231.29268293
90    431.87804878
91   -673.53658537
92    -21.87804878
93     -9.97560976
94      4.56097561
95    -54.56097561
96    779.43902439
97   -430.31707317
98   -545.24390244
99   -721.34146341
100  -100.90243902
101   230.80487805
102   187.00000000
103   474.80487805
104  -740.90243902
105   479.29268293
106  -153.53658537
107    90.70731707
108  -647.29268293
109   370.41463415
110  -612.56097561
111   -19.73170732
112   131.34146341
113  -447.14634146
114    35.19512195
115  -224.56097561
116   -34.17073171
117   293.58536585
118  -324.17073171
119   191.92682927
120  -201.73170732
121   665.09756098
122   -61.00000000
123   -16.70731707
124  -531.14634146
125   162.36585366
126    84.31707317
127  -451.97560976
128   505.92682927
129   288.07317073
130  -108.95121951
131  -214.85365854
132    65.14634146
133   253.09756098
134   232.95121951
135   760.07317073
136   684.90243902
137  -787.78048780
138  -653.68292683
139  -436.56097561
140   139.00000000
141  -395.92682927
142   122.95121951
143  -322.07317073
144  -583.58536585
145  -340.07317073
146   -72.21951220
147  -387.68292683
148  -500.85365854
149   407.73170732
150  -526.90243902
151   -73.00000000
152   -15.00000000
153    43.09756098
154    -3.97560976
155  -123.39024390
156  -127.82926829
157    68.17073171
158  -795.78048780
159  -442.85365854
160   381.73170732
161   617.53658537
162  -168.31707317
163   -94.17073171
164   296.95121951
165   472.26829268
166  -615.24390244
167   248.56097561
168   -73.63414634
169    17.19512195
170  -629.63414634
171   764.46341463
172   -80.46341463
173   116.46341463
174   620.31707317
175    52.51219512
176   458.80487805
177  -208.46341463
178   -30.02439024
179  -621.97560976
180  -322.07317073
181   661.63414634
182  -156.31707317
183   -55.63414634
184   703.34146341
185   707.34146341
186   247.39024390
187   118.31707317
188  -366.75609756
189   -19.87804878
190  -559.82926829
191  -489.97560976
192    64.12195122
193    -0.07317073
194  -370.26829268
195  -412.02439024
196   -44.12195122
197   100.26829268
198   279.92682927
199  -479.97560976
200   -30.26829268
201  -246.70731707
202  -550.31707317
203  -218.80487805
204   315.00000000
205  -137.24390244
206   462.41463415
207   160.56097561
208  -745.19512195
209  -169.58536585
210    31.29268293
211    54.07317073
212   477.04878049
213  -397.87804878
214    40.75609756
215  -139.34146341
216    23.09756098
217    19.63414634
218   538.12195122
219  -300.46341463
220    74.46341463
221   -19.53658537
222   396.02439024
223    78.46341463
224   115.00000000
225    17.82926829
226    30.85365854
227    79.63414634
228   -91.24390244
229   209.24390244
230  -365.73170732
231  -157.39024390
232   418.80487805
233  -497.00000000
234  -274.60975610
235   148.17073171
236   150.80487805
237  -102.95121951
238   465.43902439
239  -514.31707317
240   453.14634146
241  -523.24390244
242    -4.26829268
243  -723.34146341
244  -133.14634146
245  -525.09756098
246   234.46341463
247   107.58536585
248  -194.41463415
249     6.12195122
250   142.07317073
251  -673.39024390
252   398.90243902
253  -498.90243902
254   -30.90243902
255   413.87804878
256  -176.46341463
257   -40.75609756
258  -115.29268293
259   589.63414634
260  -244.65853659
261   662.02439024
262   469.48780488
263    -0.02439024
264   167.82926829
265   -87.68292683
266  -198.02439024
267   -19.48780488
268   337.82926829
269  -197.39024390
270  -730.07317073
271  -318.02439024
272   359.00000000
273  -295.34146341
274   273.43902439
275  -695.39024390
276   132.26829268
277  -563.48780488
278  -588.90243902
279  -386.60975610
280   140.60975610
281   193.97560976
282   138.70731707
283   679.68292683
284   354.80487805
285   676.41463415
286    49.68292683
287   -18.02439024
288   553.09756098
289   404.85365854
290   768.31707317
291  -412.17073171
292    29.73170732
293    39.24390244
294  -168.02439024
295   -76.17073171
296    11.92682927
297   609.24390244
298   459.63414634
299  -541.97560976
300   526.12195122
301  -474.07317073
302  -537.68292683
303   -75.14634146
304  -224.17073171
305  -318.02439024
306   224.36585366
307    75.48780488
308  -408.21951220
309  -379.39024390
310   523.29268293
311   117.29268293
312  -391.29268293
313   356.85365854
314   115.97560976
315   -18.85365854
316  -342.75609756
317    13.19512195
318   527.92682927
319   -16.75609756
320  -797.14634146
321   453.09756098
322    86.51219512
323   179.00000000
324   545.34146341
325     2.90243902
326  -201.63414634
327  -399.24390244
328   289.14634146
329   119.00000000
330   127.92682927
331   507.04878049
332   -25.39024390
333  -762.31707317
334   526.07317073
335    88.02439024
336   701.24390244
337    44.51219512
338  -153.92682927
339   532.60975610
340  -138.17073171
341   291.92682927
342   677.09756098
343   -24.90243902
344   -73.82926829
345   142.36585366
346  -292.41463415
347  -198.70731707
348    85.63414634
349   749.87804878
350   371.68292683
351  -729.43902439
352  -325.09756098
353   763.68292683
354  -558.12195122
355  -153.04878049
356   600.21951220
357   198.17073171
358  -633.19512195
359   286.21951220
360   605.92682927
361  -459.97560976
362   681.63414634
363   209.87804878
364    22.12195122
365  -222.26829268
366   143.58536585
367   534.07317073
368    -5.48780488
369  -273.34146341
370   686.95121951
371   -65.87804878
372  -133.73170732
373  -194.65853659
374  -109.09756098
375  -287.04878049
376   -31.48780488
377  -565.48780488
378   683.78048780
379  -580.75609756
380   -15.00000000
381  -215.43902439
382    94.31707317
383  -213.68292683
384   254.12195122
385  -677.43902439
386  -561.87804878
387   664.02439024
388   392.41463415
389   -66.12195122
390   526.60975610
391   -11.73170732
392   463.82926829
393   655.92682927
394  -450.17073171
395  -170.17073171
396    59.92682927
397   198.41463415
398   580.51219512
399   698.41463415
400  -542.21951220
401  -403.34146341
402    77.58536585
403    36.41463415
404    83.73170732
405   549.92682927
406  -173.34146341
407  -509.68292683
408   138.26829268
409  -315.43902439
410   554.65853659
411    41.19512195
412  -448.75609756
413   262.65853659
414    37.58536585
415   459.92682927
416   409.34146341
417   313.24390244
418  -491.14634146
419  -297.92682927
420  -249.63414634
421   599.24390244
422    -7.53658537
423  -426.17073171
424   236.65853659
425    20.12195122
426    39.68292683
427  -630.41463415
428  -118.70731707
429  -127.58536585
430  -539.39024390
431  -242.90243902
432  -659.82926829
433  -528.60975610
434   474.21951220
435  -128.90243902
436   261.48780488
437   715.34146341
438  -134.36585366
439    26.56097561
440  -212.17073171
441   -93.04878049
442   -31.04878049
443   524.17073171
444  -256.60975610
445  -202.07317073
446    59.53658537
447    10.90243902
448   439.82926829
449   497.34146341
450   199.63414634
451   -21.14634146
452  -131.24390244
453   806.26829268
454    26.65853659
455  -105.24390244
456  -594.02439024
457   -10.65853659
458   568.70731707
459  -622.65853659
460  -522.60975610
461    27.87804878
462   108.02439024
463   710.07317073
464   546.07317073
465   572.41463415
466   152.51219512
467    36.41463415
468  -469.63414634
469  -724.85365854
470   -58.95121951
471   572.51219512
472  -180.21951220
473   397.58536585
474  -110.36585366
475  -317.39024390
476   498.02439024
477  -528.75609756
478  -735.24390244
479  -580.12195122
480  -175.24390244
481    22.07317073
482  -367.29268293
483   130.41463415
484  -165.29268293
485   250.26829268
486  -186.07317073
487   610.95121951
488  -772.21951220
489  -146.46341463
490   -98.07317073
491   379.63414634
492   -29.14634146
493  -353.14634146
494   614.60975610
495  -473.29268293
496  -640.02439024
497   831.24390244
498  -352.95121951
499  -397.14634146
500    53.09756098
501   543.82926829
502  -165.53658537
503   215.63414634
504    -1.04878049
505   342.70731707
506  -439.34146341
507  -676.60975610
508    41.19512195
509   426.02439024
510   -47.53658537
511  -765.34146341
512    56.36585366
513  -805.87804878
514  -465.82926829
515  -530.41463415
516  -696.26829268
517   184.12195122
518    48.70731707
519  -516.21951220
520  -121.14634146
521   593.14634146
522   252.21951220
523  -707.92682927
524    35.68292683
525   302.75609756
526   356.51219512
527   -95.24390244
528  -150.36585366
529   430.31707317
530   562.41463415
531  -450.26829268
532  -525.58536585
533   172.31707317
534  -683.68292683
535  -624.90243902
536  -174.80487805
537   191.19512195
538   -38.07317073
539  -663.53658537
540  -586.12195122
541   -63.68292683
542  -816.02439024
543  -604.60975610
544   735.29268293
545  -480.41463415
546   545.43902439
547    27.34146341
548    53.24390244
549  -684.17073171
550   396.95121951
551  -376.41463415
552   759.63414634
553   232.41463415
554  -489.53658537
555  -287.58536585
556  -304.95121951
557   124.07317073
558   177.09756098
559   572.31707317
560  -168.46341463
561  -338.90243902
562   600.17073171
563  -413.34146341
564    91.73170732
565  -772.90243902
566  -303.04878049
567   145.63414634
568   271.78048780
569  -505.68292683
570  -150.85365854
571  -115.63414634
572  -415.63414634
573   237.39024390
574   -72.65853659
575   693.97560976
576  -497.53658537
577     1.34146341
578   157.53658537
579   203.73170732
580  -492.75609756
581  -413.97560976
582  -500.90243902
583  -364.26829268
584    74.95121951
585   -63.48780488
586  -341.48780488
587   744.51219512
588   171.92682927
589  -735.24390244
590  -412.17073171
591  -516.51219512
592   661.14634146
593    97.43902439
594   -17.34146341
595   474.65853659
596  -608.12195122
597  -230.90243902
598   547.53658537
599  -625.14634146
600   -18.65853659
601   -36.21951220
602   346.51219512
603  -626.75609756
604   106.95121951
605    65.04878049
606   133.09756098
607   367.24390244
608    93.24390244
609   628.56097561
610    66.56097561
611    75.00000000
612  -407.58536585
613    93.78048780
614   -76.17073171
615   665.39024390
616   653.09756098
617   193.73170732
618  -139.48780488
619   -41.82926829
620  -433.97560976
621  -123.04878049
622   180.41463415
623  -671.00000000
624   187.78048780
625  -210.02439024
626   -73.53658537
627  -584.51219512
628   313.97560976
629    61.82926829
630   165.24390244
631   146.56097561
632  -313.82926829
633   138.36585366
634   143.58536585
635   336.17073171
636  -494.80487805
637  -205.63414634
638   474.12195122
639    31.19512195
640  -586.60975610
641    71.24390244
642   304.90243902
643    72.75609756
644   -96.56097561
645   365.09756098
646  -350.36585366
647  -165.73170732
648  -498.41463415
649   508.56097561
650  -118.41463415
651   462.60975610
652   203.58536585
653  -731.53658537
654  -466.75609756
655   686.36585366
656    29.04878049
657   250.46341463
658   770.56097561
659  -608.02439024
660  -369.48780488
661  -465.09756098
662  -795.87804878
663  -837.73170732
664   570.65853659
665    20.70731707
666   -30.31707317
667  -569.87804878
668   102.90243902
669   175.58536585
670   326.26829268
671   -16.80487805
672  -507.14634146
673   588.65853659
674  -146.02439024
675  -655.14634146
676     5.34146341
677  -192.56097561
678  -488.17073171
679   -85.53658537
680   509.00000000
681   339.97560976
682   -82.36585366
683   209.63414634
684   150.75609756
685    87.97560976
686   609.14634146
687  -814.17073171
688   646.02439024
689  -510.75609756
690   755.00000000
691   -78.26829268
692   729.09756098
693   577.87804878
694  -606.31707317
695  -552.17073171
696    22.51219512
697   -74.12195122
698    92.70731707
699   168.60975610
700  -197.53658537
701   536.60975610
702  -148.46341463
703   600.80487805
704   -80.02439024
705  -222.95121951
706  -659.48780488
707   277.97560976
708   112.07317073
709  -634.70731707
710  -158.95121951
711   167.43902439
712  -495.73170732
713    79.58536585
714  -397.97560976
715   241.92682927
716  -236.07317073
717  -723.78048780
718  -316.70731707
719   830.60975610
720   470.02439024
721   396.26829268
722  -639.58536585
723   200.31707317
724  -660.51219512
725   120.56097561
726  -249.48780488
727  -133.97560976
728  -552.80487805
729  -425.82926829
730   543.58536585
731   137.48780488
732    62.41463415
733  -121.04878049
734  -612.56097561
735   791.43902439
736  -129.09756098
737  -124.95121951
738   201.00000000
739  -124.80487805
740  -215.92682927
741   389.58536585
742   227.68292683
743  -475.82926829
744    99.00000000
745   432.31707317
746  -120.90243902
747  -573.92682927
748    25.82926829
749   605.00000000
750   131.58536585
751   785.78048780
752   -42.41463415
753  -275.04878049
754   148.65853659
755  -140.12195122
756  -575.00000000
757   215.73170732
758   -96.60975610
759   578.51219512
760    32.21951220
761   209.24390244
762   709.14634146
763   108.02439024
764   460.95121951
765    11.92682927
766   146.65853659
767  -143.39024390
768   520.95121951
769  -274.02439024
770  -233.53658537
771   543.63414634
772  -698.02439024
773   -98.21951220
774  -418.41463415
775  -338.51219512
776    17.78048780
777  -117.24390244
778    -8.02439024
779  -565.87804878
780    11.00000000
781   428.26829268
782  -543.24390244
783  -760.56097561
784   633.68292683
785   498.36585366
786   199.04878049
787   589.14634146
788   -39.19512195
789   120.95121951
790  -310.75609756
791   462.90243902
792   574.75609756
793   -50.17073171
794   -86.70731707
795    32.17073171
796    76.70731707
797  -720.51219512
798  -399.34146341
799   717.92682927
800  -203.53658537
801   131.43902439
802   324.26829268
803   617.43902439
804   190.12195122
805   493.34146341
806   -28.46341463
807  -586.31707317
808   -73.97560976
809   -13.48780488
810  -259.09756098
811  -167.63414634
812  -395.53658537
813   700.80487805
814  -882.46341463
815  -824.17073171
816   582.80487805
817   393.29268293
818   520.07317073
819  -747.04878049
820  -163.19512195
821  -312.21951220
822    25.82926829
823    95.19512195
824  -141.00000000
825   -26.56097561
826   451.97560976
827   286.51219512
828   558.31707317
829   226.12195122
830   265.39024390
831  -430.21951220
832   -61.48780488
833  -115.87804878
834   412.31707317
835   676.07317073
836   103.19512195
837   373.58536585
838   140.36585366
839    65.24390244
840   519.24390244
841    78.21951220
842   128.56097561
843  -704.36585366
844  -191.14634146
845  -604.80487805
846   284.12195122
847    20.75609756
848   -50.46341463
849   132.41463415
850    51.09756098
851   471.92682927
852  -785.00000000
853   100.21951220
854   735.19512195
855  -666.26829268
856   -41.58536585
857  -252.75609756
858  -467.09756098
859   650.70731707
860   656.46341463
861    31.34146341
862   276.56097561
863   -82.60975610
864  -400.36585366
865  -156.31707317
866   615.58536585
867   -87.53658537
868   449.39024390
869  -632.31707317
870  -472.12195122
871   222.36585366
872  -385.78048780
873  -373.39024390
874    31.73170732
875  -151.04878049
876     8.21951220
877   346.41463415
878   151.29268293
879    10.56097561
880  -589.68292683
881   132.75609756
882  -243.73170732
883    94.02439024
884   301.48780488
885   -18.75609756
886   616.56097561
887   523.82926829
888   -53.78048780
889    30.90243902
890   -23.14634146
891  -305.43902439
892   -81.58536585
893   363.73170732
894    -2.56097561
895  -220.12195122
896  -642.56097561
897    54.31707317
898  -300.07317073
899    15.09756098
900     0.51219512
901    -3.92682927
902   215.97560976
903  -513.14634146
904  -156.75609756
905  -354.41463415
906   -53.68292683
907   -33.34146341
908   -65.34146341
909   -74.75609756
910   300.12195122
911    32.02439024
912    -4.90243902
913  -142.75609756
914  -108.51219512
915  -188.51219512
916   -30.56097561
917  -578.07317073
918  -644.41463415
919  -398.70731707
920   -43.09756098
921  -185.43902439
922  -161.48780488
923   645.53658537
924   662.02439024
925  -157.63414634
926   -14.85365854
927  -736.12195122
928  -394.56097561
929   112.85365854
930   582.75609756
931  -141.00000000
932   187.19512195
933   140.02439024
934   361.29268293
935  -177.63414634
936  -337.14634146
937   696.17073171
938   177.43902439
939  -581.82926829
940   770.36585366
941   420.51219512
942  -660.26829268
943   146.31707317
944   486.36585366
945   433.34146341
946  -408.85365854
947  -446.95121951
948  -163.00000000
949   549.53658537
950   173.78048780
951    55.87804878
952  -592.07317073
953    83.68292683
954   583.14634146
955  -226.36585366
956   -91.14634146
957  -352.51219512
958    39.00000000
959  -603.68292683
960   682.12195122
961   405.04878049
962   -70.36585366
963    86.21951220
964   755.97560976
965  -485.39024390
966  -297.82926829
967  -126.36585366
968   -45.87804878
969  -169.53658537
970  -631.92682927
971   362.07317073
972   -78.85365854
973   434.02439024
974   -60.02439024
975    -5.97560976
976  -165.43902439
977  -140.95121951
978  -123.58536585
979  -557.87804878
980   251.53658537
981   626.80487805
982   216.41463415
983   137.43902439
984  -224.46341463
985  -100.02439024
986    94.90243902
987   421.00000000
988   745.68292683
989   -87.63414634
990   351.78048780
991    37.14634146
992  -783.29268293
993  -439.14634146
994  -375.82926829
995  -200.51219512
996   -89.82926829
997   -40.31707317
998   258.60975610
999   -83.00000000
1000 -385.73170732
1001  125.97560976
1002 -535.97560976
1003 -160.21951220
1004  -15.58536585
1005  -11.58536585
1006 -113.92682927
1007 -103.24390244
1008 -397.48780488
1009 -620.51219512
1010  -33.14634146
1011 -135.24390244
1012 -413.82926829
1013  161.63414634
1014  114.60975610
1015  607.09756098
1016 -142.51219512
1017 -372.65853659
1018  539.97560976
1019  347.00000000
1020 -125.82926829
1021  293.29268293
1022  534.80487805
1023  -64.95121951
1024  700.02439024
1025  -24.46341463
1026  482.95121951
1027 -299.24390244
1028  389.39024390
1029 -739.34146341
1030 -169.68292683
1031 -369.92682927
1032  617.58536585
1033 -243.53658537
1034  -48.75609756
1035  602.51219512
1036  491.87804878
1037  723.19512195
1038  120.95121951
1039 -100.56097561
1040  122.51219512
1041 -487.39024390
1042  240.56097561
1043   51.73170732
1044  391.04878049
1045  353.63414634
1046 -484.02439024
1047 -802.51219512
1048  687.92682927
1049  355.73170732
1050 -420.75609756
1051 -644.56097561
1052 -346.12195122
1053 -146.17073171
1054 -112.26829268
1055  293.04878049
1056 -506.12195122
1057  671.63414634
1058 -730.56097561
1059  -49.58536585
1060   31.00000000
1061   -9.82926829
1062  149.24390244
1063  506.51219512
1064  -79.19512195
1065  -18.90243902
1066   51.92682927
1067   60.70731707
1068   49.68292683
1069  -70.02439024
1070 -832.70731707
1071 -190.26829268
1072 -405.58536585
1073 -194.56097561
1074   34.65853659
1075  553.00000000
1076 -337.34146341
1077 -540.12195122
1078  103.24390244
1079  509.39024390
1080 -648.36585366
1081 -475.73170732
1082  356.36585366
1083 -673.68292683
1084  528.65853659
1085 -891.53658537
1086  -88.60975610
1087 -591.24390244
1088  448.31707317
1089 -263.43902439
1090  201.78048780
1091 -273.78048780
1092  256.12195122
1093  632.56097561
1094 -167.68292683
1095 -272.56097561
1096  734.41463415
1097 -170.90243902
1098  -93.48780488
1099 -208.02439024
1100  177.82926829
1101 -521.82926829
1102  444.70731707
1103   -5.04878049
1104  195.14634146
1105  224.70731707
1106  303.97560976
1107 -357.78048780
1108 -647.73170732
1109 -333.53658537
1110 -554.75609756
1111  -66.36585366
1112   60.85365854
1113  399.29268293
1114 -106.02439024
1115  353.58536585
1116 -618.26829268
1117 -272.95121951
1118 -347.34146341
1119 -383.29268293
1120 -805.19512195
1121  625.09756098
1122  680.21951220
1123 -153.78048780
1124  189.34146341
1125 -330.21951220
1126 -551.73170732
1127  -12.02439024
1128 -369.58536585
1129  108.31707317
1130  546.21951220
1131  756.17073171
1132 -624.17073171
1133  194.85365854
1134 -128.85365854
1135 -102.65853659
1136   81.04878049
1137 -578.31707317
1138  246.31707317
1139 -636.85365854
1140  -20.02439024
1141  752.12195122
1142  -69.19512195
1143 -658.46341463
1144 -178.60975610
1145 -648.85365854
1146  -20.41463415
1147  203.43902439
1148  292.60975610
1149  -17.87804878
1150 -657.09756098
1151  654.17073171
1152  154.07317073
1153  -34.21951220
1154   36.65853659
1155  418.95121951
1156 -491.97560976
1157  382.85365854
1158 -196.85365854
1159  308.17073171
1160 -559.92682927
1161  102.51219512
1162 -596.41463415
1163   56.07317073
1164 -570.07317073
1165  626.07317073
1166 -148.85365854
1167 -243.29268293
1168  -62.75609756
1169 -358.60975610
1170  -24.02439024
1171 -268.21951220
1172  682.60975610
1173 -625.19512195
1174 -574.31707317
1175  742.46341463
1176  630.60975610
1177 -560.51219512
1178 -308.90243902
1179  559.39024390
1180  496.17073171
1181  -66.26829268
1182   52.07317073
1183 -791.78048780
1184  -16.90243902
1185  726.17073171
1186 -496.90243902
1187  -11.73170732
1188 -218.46341463
1189  802.02439024
1190 -185.43902439
1191   76.80487805
1192  127.09756098
1193 -236.21951220
1194   41.43902439
1195  -35.58536585
1196  -38.31707317
1197  -75.48780488
1198  567.14634146
1199  130.51219512
1200   40.21951220
1201  607.19512195
1202 -751.39024390
1203   46.90243902
1204   31.63414634
1205  229.34146341
1206   80.02439024
1207  174.12195122
1208 -325.34146341
1209 -747.63414634
1210  730.17073171
1211   97.63414634
1212 -480.41463415
1213   98.12195122
1214   82.12195122
1215  826.02439024
1216  557.48780488
1217  814.21951220
1218   98.95121951
1219   55.04878049
1220  -50.17073171
1221  246.17073171
1222  340.36585366
1223 -676.90243902
1224 -191.78048780
1225  -15.87804878
1226 -659.87804878
1227  769.24390244
1228 -728.60975610
1229  366.36585366
1230   64.12195122
1231  506.95121951
1232  550.70731707
1233  -96.12195122
1234   88.46341463
1235 -566.90243902
1236 -419.58536585
1237 -258.07317073
1238  406.80487805
1239  -62.56097561
1240  567.58536585
1241 -103.14634146
1242  -17.53658537
1243   87.09756098
1244   14.17073171
1245 -133.78048780
1246  567.00000000
1247  228.02439024
1248 -340.36585366
1249  -95.87804878
1250  657.78048780
1251  533.92682927
1252 -100.02439024
1253 -295.48780488
1254  102.80487805
1255 -128.17073171
1256  241.00000000
1257  -25.63414634
1258  503.29268293
1259  609.78048780
1260   21.29268293
1261  152.65853659
1262 -771.43902439
1263  633.29268293
1264 -296.85365854
1265   87.29268293
1266   13.24390244
1267 -461.48780488
1268  145.34146341
1269  783.34146341
1270  153.58536585
1271  -33.00000000
1272  591.14634146
1273   94.21951220
1274  -53.82926829
1275   38.51219512
1276   82.26829268
1277 -426.41463415
1278  528.51219512
1279 -776.07317073
1280 -215.53658537
1281 -179.00000000
1282 -663.19512195
1283   15.29268293
1284  164.21951220
1285   -8.80487805
1286 -158.56097561
1287  -39.97560976
1288  -83.39024390
1289 -444.07317073
1290  643.78048780
1291 -618.02439024
1292  236.70731707
1293 -570.56097561
1294 -506.07317073
1295  475.39024390
1296  336.17073171
1297 -147.82926829
1298  311.73170732
1299  -59.19512195
1300  -10.31707317
1301  271.87804878
1302  150.51219512
1303  178.56097561
1304  -38.21951220
1305  278.56097561
1306 -776.12195122
1307 -799.14634146
1308  -65.43902439
1309   84.51219512
1310  192.60975610
1311  133.19512195
1312   92.46341463
1313  433.53658537
1314  731.92682927
1315 -596.02439024
1316 -589.97560976
1317 -110.51219512
1318  259.24390244
1319 -143.34146341
1320 -323.19512195
1321  335.53658537
1322 -395.24390244
1323 -486.17073171
1324  737.78048780
1325 -153.97560976
1326 -126.12195122
1327   42.60975610
1328 -411.97560976
1329 -314.80487805
1330    8.21951220
1331  464.80487805
1332  -31.29268293
1333  488.85365854
1334   74.85365854
1335 -171.43902439
1336  -21.92682927
1337 -658.17073171
1338  -55.68292683
1339  493.58536585
1340 -140.41463415
1341 -614.21951220
1342  -49.97560976
1343  495.87804878
1344  152.31707317
1345  418.75609756
1346  667.14634146
1347  669.92682927
1348  662.07317073
1349 -180.75609756
1350  366.65853659
1351  302.46341463
1352 -113.73170732
1353  -16.80487805
1354  344.41463415
1355  -17.14634146
1356   -3.73170732
1357  254.36585366
1358    2.36585366
1359 -784.46341463
1360 -406.46341463
1361  -87.39024390
1362  626.60975610
1363 -592.21951220
1364 -263.09756098
1365 -140.02439024
1366 -620.51219512
1367 -498.60975610
1368 -593.68292683
1369 -240.21951220
1370  573.53658537
1371  193.82926829
1372  125.87804878
1373 -103.87804878
1374 -335.97560976
1375 -803.04878049
1376 -172.12195122
1377   99.68292683
1378 -163.68292683
1379 -374.95121951
1380  525.09756098
1381  110.70731707
1382  161.04878049
1383 -493.58536585
1384   81.34146341
1385  576.46341463
1386  -69.34146341
1387 -452.51219512
1388  431.39024390
1389  691.39024390
1390  383.63414634
1391 -241.48780488
1392  367.63414634
1393 -127.34146341
1394   48.21951220
1395  473.97560976
1396 -221.09756098
1397  -51.92682927
1398 -129.53658537
1399 -146.17073171
1400   37.00000000
1401  -98.26829268
1402  725.43902439
1403 -355.58536585
1404  -70.60975610
1405 -340.12195122
1406   97.34146341
1407  436.70731707
1408   45.68292683
1409   45.53658537
1410  -73.73170732
1411  826.17073171
1412  -18.90243902
1413  534.41463415
1414 -141.24390244
1415 -278.95121951
1416  187.09756098
1417 -691.97560976
1418  -59.43902439
1419 -588.31707317
1420   70.17073171
1421  217.97560976
1422  479.09756098
1423 -556.75609756
1424 -212.26829268
1425  -26.51219512
1426  515.43902439
1427   92.26829268
1428   16.51219512
1429  128.26829268
1430 -158.02439024
1431  363.39024390
1432 -573.34146341
1433  355.14634146
1434   -2.56097561
1435   63.58536585
1436  116.46341463
1437  419.43902439
1438 -205.00000000
1439  692.75609756
1440   95.58536585
1441  367.68292683
1442   89.19512195
1443   -3.48780488
1444   21.73170732
1445  796.31707317
1446  -42.51219512
1447  194.21951220
1448 -666.07317073
1449 -444.85365854
1450  535.39024390
1451 -248.21951220
1452  603.43902439
1453  174.02439024
1454 -153.92682927
1455  719.58536585
1456 -612.07317073
1457 -521.73170732
1458 -471.48780488
1459   95.92682927
1460 -685.34146341
1461 -110.07317073
1462   72.36585366
1463  616.31707317
1464 -587.53658537
1465  637.97560976
1466 -545.24390244
1467  520.36585366
1468  727.82926829
1469 -626.70731707
1470  354.75609756
1471  246.90243902
1472  405.53658537
1473   27.63414634
1474 -465.24390244
1475 -140.46341463
1476  560.80487805
1477 -197.29268293
1478   -6.90243902
1479   30.07317073
1480 -309.87804878
1481  298.80487805
1482  499.19512195
1483 -153.19512195
1484 -473.04878049
1485  548.75609756
1486 -280.46341463
1487 -107.78048780
1488    0.21951220
1489  507.14634146
1490  409.87804878
1491 -132.65853659
1492 -676.60975610
1493 -403.29268293
1494  482.65853659
1495 -479.53658537
1496  343.48780488
1497  447.73170732
1498 -831.97560976
1499  818.56097561
1500  502.85365854
1501  -27.53658537
1502  423.29268293
1503  609.48780488
1504  822.12195122
1505  587.43902439
1506 -372.60975610
1507   79.63414634
1508 -587.53658537
1509 -593.00000000
1510 -157.78048780
1511  101.82926829
1512 -298.95121951
1513   40.31707317
1514  -77.53658537
1515  -25.24390244
1516  216.75609756
1517  305.53658537
1518   47.09756098
1519   -4.41463415
1520  -15.73170732
1521 -725.87804878
1522  169.24390244
1523  268.12195122
1524 -300.85365854
1525    2.21951220
1526  716.80487805
1527  205.53658537
1528 -230.56097561
1529  186.90243902
1530 -556.31707317
1531 -195.58536585
1532 -672.51219512
1533 -403.43902439
1534  -19.43902439
1535 -205.53658537
1536  -68.26829268
1537  462.90243902
1538  634.17073171
1539  475.92682927
1540 -474.90243902
1541  619.48780488
1542 -165.78048780
1543  628.90243902
1544  219.97560976
1545 -651.82926829
1546 -674.07317073
1547   34.51219512
1548 -587.43902439
1549 -675.82926829
1550 -359.92682927
1551 -352.36585366
1552  175.82926829
1553  659.53658537
1554  374.02439024
1555 -450.31707317
1556   51.39024390
1557 -668.80487805
1558   -2.26829268
1559 -635.68292683
1560 -757.73170732
1561  -95.39024390
1562  -84.12195122
1563  173.97560976
1564 -443.43902439
1565  528.17073171
1566  257.39024390
1567 -609.39024390
1568  126.21951220
1569 -197.82926829
1570 -247.00000000
1571  325.78048780
1572 -718.75609756
1573    8.26829268
1574 -664.21951220
1575 -600.21951220
1576  141.39024390
1577 -538.56097561
1578 -554.46341463
1579  239.34146341
1580 -234.02439024
1581  359.39024390
1582  555.87804878
1583  193.14634146
1584   12.80487805
1585  436.41463415
1586 -469.19512195
1587 -500.21951220
1588  115.48780488
1589   60.26829268
1590  -10.80487805
1591  -36.21951220
1592 -185.82926829
1593 -296.65853659
1594    8.31707317
1595  672.46341463
1596 -120.41463415
1597  283.48780488
1598 -110.70731707
1599  -64.41463415
1600 -445.43902439
1601 -710.17073171
1602 -549.73170732
1603  320.95121951
1604  706.36585366
1605 -369.82926829
1606  731.24390244
1607 -696.07317073
1608  315.04878049
1609  -88.80487805
1610  -92.85365854
1611  506.95121951
1612 -165.63414634
1613  -74.56097561
1614  480.90243902
1615  403.78048780
1616  196.36585366
1617  274.36585366
1618  -54.07317073
1619 -108.95121951
1620 -479.19512195
1621  -56.21951220
1622  104.31707317
1623 -132.56097561
1624  209.14634146
1625  170.21951220
1626  573.29268293
1627 -351.92682927
1628  703.34146341
1629   24.21951220
1630 -652.56097561
1631  792.65853659
1632 -530.36585366
1633  558.31707317
1634  209.78048780
1635  -32.26829268
1636 -593.48780488
1637  506.51219512
1638 -112.02439024
1639  479.87804878
1640  545.97560976
1641  -75.97560976
1642  468.41463415
1643 -673.73170732
1644 -225.29268293
1645 -341.53658537
1646 -347.43902439
1647 -640.02439024
1648 -544.65853659
1649 -131.19512195
1650   52.56097561
1651  -62.36585366
1652  364.85365854
1653 -583.39024390
1654  249.39024390
1655  -44.95121951
1656 -153.53658537
1657  -91.24390244
1658 -756.41463415
1659  607.82926829
1660  402.80487805
1661    9.43902439
1662  -61.58536585
1663  325.00000000
1664  261.73170732
1665 -601.24390244
1666  -37.04878049
1667  -26.02439024
1668  252.17073171
1669  811.92682927
1670  541.04878049
1671   76.70731707
1672 -464.60975610
1673  508.75609756
1674  874.60975610
1675  466.60975610
1676  -14.70731707
1677 -469.24390244
1678  496.65853659
1679   90.21951220
1680   31.39024390
1681  622.70731707
1682 -175.87804878
1683 -452.02439024
1684  146.17073171
1685 -387.73170732
1686 -544.21951220
1687 -574.46341463
1688 -631.87804878
1689 -106.80487805
1690  270.95121951
1691 -325.34146341
1692  -19.73170732
1693  460.26829268
1694 -473.73170732
1695  182.95121951
1696  -46.70731707
1697 -887.78048780
1698  -39.53658537
1699  -54.95121951
1700  465.68292683
1701   12.17073171
1702  581.58536585
1703 -687.87804878
1704 -344.56097561
1705 -108.75609756
1706  551.04878049
1707   -6.95121951
1708  838.02439024
1709  572.95121951
1710 -492.07317073
1711 -523.82926829
1712  377.39024390
1713  593.00000000
1714  -17.04878049
1715    0.41463415
1716 -581.63414634
1717  -64.60975610
1718  471.09756098
1719 -706.02439024
1720 -174.26829268
1721   18.41463415
1722  259.48780488
1723 -587.82926829
1724 -413.00000000
1725 -456.56097561
1726 -145.09756098
1727 -263.34146341
1728 -648.21951220
1729 -453.09756098
1730 -495.29268293
1731  -76.65853659
1732 -489.78048780
1733  405.87804878
1734 -148.41463415
1735  247.87804878
1736 -599.87804878
1737  448.21951220
1738 -196.36585366
1739  363.58536585
1740  640.31707317
1741   83.19512195
1742    7.68292683
1743  334.36585366
1744 -124.46341463
1745 -365.78048780
1746  485.39024390
1747  198.21951220
1748 -131.82926829
1749  636.85365854
1750  531.14634146
1751 -169.29268293
1752  456.70731707
1753   37.73170732
1754  363.92682927
1755  -49.53658537
1756 -202.80487805
1757   63.43902439
1758 -684.85365854
1759  616.02439024
1760  -32.85365854
1761  222.75609756
1762  218.75609756
1763  -50.70731707
1764 -567.63414634
1765 -118.70731707
1766   13.58536585
1767 -581.09756098
1768 -463.29268293
1769 -243.48780488
1770 -272.60975610
1771  708.80487805
1772  803.19512195
1773  511.39024390
1774  232.46341463
1775   79.04878049
1776 -354.21951220
1777 -593.58536585
1778   10.41463415
1779 -585.00000000
1780   74.65853659
1781  481.24390244
1782 -576.65853659
1783  663.97560976
1784  403.29268293
1785  -82.80487805
1786  677.78048780
1787  618.17073171
1788 -431.39024390
1789  796.80487805
1790 -603.73170732
1791 -646.70731707
1792 -197.09756098
1793   -6.56097561
1794  -23.09756098
1795  -93.00000000
1796  -31.63414634
1797  209.00000000
1798  763.04878049
1799  134.70731707
1800  656.12195122
1801  -85.78048780
1802 -207.43902439
1803  639.19512195
1804  -69.39024390
1805 -125.48780488
1806  372.02439024
1807  -83.00000000
1808  641.48780488
1809  355.87804878
1810   74.90243902
1811 -534.90243902
1812 -690.51219512
1813  754.02439024
1814 -120.85365854
1815  518.80487805
1816   -0.56097561
1817 -154.12195122
1818   14.90243902
1819  -66.21951220
1820  544.02439024
1821 -786.12195122
1822 -323.24390244
1823  754.56097561
1824  530.07317073
1825 -471.58536585
1826 -116.70731707
1827 -129.92682927
1828 -329.43902439
1829  656.56097561
1830 -469.19512195
1831 -279.58536585
1832 -575.24390244
1833  -16.46341463
1834  -21.48780488
1835  193.82926829
1836  -27.09756098
1837  401.34146341
1838  246.17073171
1839  162.90243902
1840  215.14634146
1841  -47.19512195
1842 -151.97560976
1843 -606.56097561
1844  122.75609756
1845 -595.73170732
1846  -81.34146341
1847  521.92682927
1848  309.63414634
1849 -489.97560976
1850 -543.34146341
1851  263.14634146
1852  469.92682927
1853  -54.60975610
1854  126.51219512
1855    9.53658537
1856 -167.29268293
1857  142.12195122
1858 -745.97560976
1859 -525.92682927
1860  593.29268293
1861 -534.46341463
1862  711.24390244
1863 -130.36585366
1864 -188.21951220
1865  653.14634146
1866 -572.75609756
1867  849.73170732
1868 -766.07317073
1869 -249.73170732
1870  107.24390244
1871 -574.21951220
1872 -210.56097561
1873  177.04878049
1874  450.36585366
1875 -296.90243902
1876 -556.56097561
1877  746.12195122
1878  -69.53658537
1879 -475.43902439
1880 -519.04878049
1881 -469.24390244
1882  478.65853659
1883  350.95121951
1884   84.21951220
1885 -397.87804878
1886 -723.68292683
1887 -555.68292683
1888  726.85365854
1889  640.21951220
1890 -210.95121951
1891   71.19512195
1892 -494.46341463
1893  -21.48780488
1894  254.56097561
1895  -56.70731707
1896  763.19512195
1897  327.92682927
1898  449.34146341
1899  160.95121951
1900 -674.41463415
1901 -147.00000000
1902  760.56097561
1903  -82.65853659
1904   46.85365854
1905 -304.85365854
1906 -711.73170732
1907  395.73170732
1908  792.07317073
1909  472.17073171
1910  270.60975610
1911 -514.26829268
1912  169.19512195
1913 -271.29268293
1914  620.17073171
1915  654.46341463
1916  114.51219512
1917  302.26829268
1918 -191.53658537
1919  672.95121951
1920 -107.39024390
1921 -208.56097561
1922 -241.73170732
1923 -191.97560976
1924  155.48780488
1925  101.78048780
1926  409.19512195
1927  202.36585366
1928  566.60975610
1929   94.17073171
1930 -506.56097561
1931 -200.65853659
1932  216.46341463
1933 -174.51219512
1934    3.09756098
1935  -19.34146341
1936   59.14634146
1937  715.87804878
1938  -17.58536585
1939 -167.00000000
1940  613.78048780
1941 -419.58536585
1942  652.07317073
1943 -597.63414634
1944  213.00000000
1945  301.19512195
1946   58.56097561
1947  -66.41463415
1948 -651.00000000
1949 -528.51219512
1950   31.78048780
1951  148.85365854
1952   53.39024390
1953   38.85365854
1954  393.87804878
1955  115.00000000
1956 -520.41463415
1957 -148.56097561
1958 -416.85365854
1959 -531.73170732
1960  541.68292683
1961 -199.19512195
1962  628.12195122
1963 -231.48780488
1964 -586.21951220
1965 -607.58536585
1966  -61.73170732
1967 -611.92682927
1968  -67.43902439
1969  434.21951220
1970  548.60975610
1971 -508.46341463
1972  -74.70731707
1973 -503.58536585
1974 -699.97560976
1975  289.00000000
1976  -28.90243902
1977   95.87804878
1978  409.78048780
1979  738.46341463
1980 -372.80487805
1981   29.43902439
1982 -243.14634146
1983  469.34146341
1984  -65.48780488
1985  563.68292683
1986  685.87804878
1987 -372.07317073
1988  426.85365854
1989 -179.48780488
1990  161.48780488
1991   63.14634146
1992 -509.73170732
1993   95.87804878
1994  -98.90243902
1995  340.56097561
1996  548.21951220
1997 -476.90243902
1998  720.26829268
1999  518.26829268
2000  147.58536585
2001  730.56097561
2002  579.43902439
2003   53.04878049
2004 -336.80487805
2005 -552.07317073
2006   66.02439024
2007  -90.75609756
2008  577.29268293
2009  -23.92682927
2010   86.56097561
2011 -493.04878049
2012 -453.78048780
2013 -646.07317073
2014  746.02439024
2015   -6.80487805
2016  375.48780488
2017 -118.75609756
2018 -209.14634146
2019   61.29268293
2020  143.68292683
2021 -618.36585366
2022 -436.75609756
2023  457.63414634
2024  -65.43902439
2025  400.51219512
2026 -463.39024390
2027 -160.51219512
2028   55.43902439
2029  115.48780488
2030 -112.21951220
2031 -122.80487805
2032 -261.68292683
2033  105.19512195
2034  563.19512195
2035  451.53658537
2036  -96.31707317
2037  193.87804878
2038  286.60975610
2039  582.02439024
2040 -123.58536585
2041   36.36585366
2042  625.87804878
2043  -95.34146341
2044 -530.36585366
2045 -209.97560976
2046 -238.60975610
2047  -67.78048780
2048  683.29268293
2049  428.85365854
2050 -549.87804878
2051  -38.60975610
2052  -73.53658537
2053  292.90243902
2054 -482.95121951
2055  -89.92682927
2056 -310.46341463
2057  175.48780488
2058  304.60975610
2059 -686.80487805
2060 -681.82926829
2061  420.60975610
2062  187.48780488
2063 -502.36585366
2064 -119.19512195
2065   60.17073171
2066 -325.87804878
2067  133.73170732
2068   16.80487805
2069 -110.46341463
2070 -234.17073171
2071 -743.04878049
2072   27.43902439
2073 -633.04878049
2074  -89.97560976
2075   87.73170732
2076  192.02439024
2077  310.31707317
2078 -694.60975610
2079   61.82926829
2080   79.19512195
2081 -656.70731707
2082  473.97560976
2083  253.43902439
2084  106.75609756
2085  602.07317073
2086  695.43902439
2087   12.31707317
2088  -28.90243902
2089  400.12195122
2090  -91.53658537
2091  -10.85365854
2092  -78.21951220
2093  551.97560976
2094  -70.41463415
2095 -207.97560976
2096   28.90243902
2097 -744.36585366
2098 -575.68292683
2099 -396.02439024
2100  558.12195122
2101  383.43902439
2102  -52.85365854
2103  658.51219512
2104  187.92682927
2105  537.24390244
2106   55.73170732
2107 -146.95121951
2108 -168.12195122
2109    2.51219512
2110  813.48780488
2111 -453.97560976
2112 -167.97560976
2113    4.07317073
2114  660.46341463
2115  -90.36585366
2116 -440.07317073
2117 -316.41463415
2118  140.31707317
2119  517.68292683
2120 -187.53658537
2121  734.26829268
2122 -594.07317073
2123   -6.21951220
2124  219.24390244
2125  538.70731707
2126  505.53658537
2127  354.17073171
2128  198.46341463
2129   68.56097561
2130  522.70731707
2131 -640.70731707
2132 -329.53658537
2133  556.41463415
2134  646.31707317
2135  312.75609756
2136 -523.19512195
2137  469.58536585
2138 -400.85365854
2139 -267.48780488
2140  726.02439024
2141  -67.58536585
2142  531.34146341
2143 -515.68292683
2144  518.02439024
2145  420.95121951
2146   21.73170732
2147  435.97560976
2148  -47.58536585
2149 -424.90243902
2150    3.24390244
2151  396.95121951
2152 -538.60975610
2153   59.97560976
2154   49.24390244
2155 -155.29268293
2156 -706.56097561
2157 -535.14634146
2158  612.36585366
2159  -38.46341463
2160 -429.73170732
2161  132.26829268
2162 -263.63414634
2163 -208.85365854
2164 -281.09756098
2165   50.95121951
2166   76.80487805
2167 -580.80487805
2168  628.46341463
2169  690.60975610
2170  340.26829268
2171  659.14634146
2172  104.51219512
2173  -41.68292683
2174  -35.82926829
2175  256.95121951
2176  -48.95121951
2177  275.63414634
2178 -613.92682927
2179 -441.63414634
2180  381.63414634
2181  182.75609756
2182  485.63414634
2183 -191.39024390
2184   56.36585366
2185  516.85365854
2186 -575.09756098
2187 -451.04878049
2188  173.04878049
2189   84.36585366
2190  -73.63414634
2191  178.90243902
2192  700.60975610
2193  -88.65853659
2194  250.12195122
2195 -714.41463415
2196    5.14634146
2197   42.17073171
2198  612.85365854
2199  -92.07317073
2200 -432.80487805
2201 -626.65853659
2202 -420.90243902
2203  -32.90243902
2204 -152.80487805
2205 -774.21951220
2206 -671.19512195
2207 -607.19512195
2208  -43.78048780
2209  853.73170732
2210 -654.31707317
2211 -823.63414634
2212  411.97560976
2213 -598.07317073
2214  204.46341463
2215  -53.87804878
2216 -106.26829268
2217 -101.92682927
2218 -557.34146341
2219  534.75609756
2220   31.82926829
2221   71.00000000
2222 -182.75609756
2223  606.65853659
2224  483.09756098
2225 -504.21951220
2226 -172.80487805
2227  671.39024390
2228 -493.48780488
2229 -641.00000000
2230 -618.36585366
2231  139.78048780
2232  -42.46341463
2233   91.63414634
2234  101.34146341
2235  551.92682927
2236  376.41463415
2237  443.14634146
2238  207.34146341
2239   -9.87804878
2240  120.26829268
2241  -73.73170732
2242  150.70731707
2243   50.12195122
2244 -399.58536585
2245 -621.43902439
2246  351.78048780
2247 -699.82926829
2248 -649.34146341
2249  538.90243902
2250 -416.31707317
2251  537.34146341
2252 -163.58536585
2253 -163.63414634
2254 -543.00000000
2255  572.85365854
2256  451.97560976
2257 -545.19512195
2258 -112.90243902
2259 -451.04878049
2260 -102.31707317
2261  552.46341463
2262 -656.65853659
2263  488.21951220
2264   56.02439024
2265 -105.34146341
2266 -436.31707317
2267  -18.02439024
2268  502.21951220
2269   69.48780488
2270  243.97560976
2271  303.82926829
2272  385.97560976
2273 -121.87804878
2274    2.65853659
2275 -146.51219512
2276 -135.73170732
2277  283.00000000
2278  -62.70731707
2279 -510.51219512
2280 -253.39024390
2281   90.51219512
2282  611.09756098
2283 -218.41463415
2284  697.48780488
2285 -652.65853659
2286  413.14634146
2287  128.21951220
2288 -192.17073171
2289  131.68292683
2290 -661.48780488
2291  627.19512195
2292 -171.19512195
2293 -143.53658537
2294 -326.36585366
2295  -30.75609756
2296 -398.36585366
2297   79.78048780
2298 -617.87804878
2299 -582.75609756
2300 -588.41463415
2301   81.82926829
2302   31.19512195
2303  519.29268293
2304 -399.58536585
2305 -605.92682927
2306 -653.29268293
2307   17.78048780
2308  437.63414634
2309  247.82926829
2310  528.90243902
2311 -116.60975610
2312  603.63414634
2313  -82.80487805
2314  368.26829268
2315  599.14634146
2316 -279.00000000
2317   49.63414634
2318  568.07317073
2319  476.26829268
2320  292.80487805
2321 -558.51219512
2322  145.24390244
2323  128.07317073
2324   36.65853659
2325 -180.17073171
2326  348.70731707
2327   41.00000000
2328    6.02439024
2329 -404.02439024
2330  652.07317073
2331  102.31707317
2332 -129.14634146
2333  157.68292683
2334  148.26829268
2335  432.56097561
2336  277.87804878
2337  528.36585366
2338 -186.46341463
2339  -48.75609756
2340   40.65853659
2341 -128.21951220
2342   89.39024390
2343 -626.51219512
2344  -94.31707317
2345  120.17073171
2346 -354.85365854
2347 -285.73170732
2348  365.00000000
2349  -33.34146341
2350  132.60975610
2351  206.46341463
2352 -372.17073171
2353  172.90243902
2354 -499.19512195
2355 -214.95121951
2356  825.92682927
2357 -608.41463415
2358  -29.00000000
2359   29.73170732
2360  776.41463415
2361    4.02439024
2362 -336.41463415
2363 -473.53658537
2364  140.75609756
2365  210.85365854
2366  -41.34146341
2367 -780.07317073
2368  335.53658537
2369   55.68292683
2370  542.02439024
2371  505.63414634
2372 -161.19512195
2373 -124.80487805
2374 -467.92682927
2375   18.70731707
2376 -639.19512195
2377  -60.85365854
2378 -319.48780488
2379  633.34146341
2380  633.00000000
2381  414.65853659
2382 -387.43902439
2383 -135.53658537
2384  100.60975610
2385 -593.24390244
2386 -231.63414634
2387  228.80487805
2388  674.17073171
2389 -708.65853659
2390  409.73170732
2391  525.97560976
2392  221.19512195
2393   38.95121951
2394 -381.24390244
2395  -38.56097561
2396  239.73170732
2397  -65.19512195
2398  226.46341463
2399 -364.65853659
2400  161.53658537
2401 -293.39024390
2402   24.80487805
2403  392.75609756
2404  327.19512195
2405 -389.53658537
2406 -169.63414634
2407  -20.07317073
2408  123.63414634
2409 -705.53658537
2410   17.48780488
2411 -118.21951220
2412 -406.41463415
2413  241.97560976
2414  421.87804878
2415  576.31707317
2416  611.19512195
2417  -61.00000000
2418  777.82926829
2419  530.85365854
2420  173.97560976
2421  446.56097561
2422 -488.90243902
2423  352.75609756
2424  601.24390244
2425   92.90243902
2426  591.19512195
2427 -158.80487805
2428 -564.85365854
2429 -720.41463415
2430  -66.21951220
2431 -288.31707317
2432   58.75609756
2433  -67.39024390
2434 -744.80487805
2435 -121.73170732
2436 -540.65853659
2437 -288.90243902
2438  672.56097561
2439   45.24390244
2440   75.78048780
2441   52.07317073
2442 -163.68292683
2443 -525.63414634
2444 -453.63414634
2445  -95.92682927
2446 -170.21951220
2447 -349.58536585
2448   -7.24390244
2449  627.73170732
2450  276.41463415
2451  -73.29268293
2452  -52.17073171
2453 -181.29268293
2454  194.02439024
2455  245.68292683
2456  551.34146341
2457 -657.92682927
2458   24.21951220
2459 -122.31707317
2460 -281.97560976
2461  263.92682927
2462  368.36585366
2463  138.51219512
2464 -713.29268293
2465 -520.95121951
2466 -428.31707317
2467 -555.14634146
2468 -473.82926829
2469 -116.85365854
2470 -562.80487805
2471  803.68292683
2472  791.29268293
2473  197.87804878
2474   61.87804878
2475 -469.63414634
2476  144.70731707
2477  150.51219512
2478  518.75609756
2479 -484.80487805
2480 -517.73170732
2481  208.51219512
2482 -550.41463415
2483 -304.46341463
2484  -45.68292683
2485 -415.97560976
2486 -325.00000000
2487  316.85365854
2488  102.65853659
2489 -619.04878049
2490  600.31707317
2491  680.36585366
2492 -493.87804878
2493 -429.87804878
2494 -413.04878049
2495 -144.12195122
2496  736.95121951
2497 -444.95121951
2498  717.92682927
2499  377.92682927
2500  281.58536585
2501   85.78048780
2502 -587.82926829
2503 -524.65853659
2504   31.78048780
2505  -31.19512195
2506   18.12195122
2507  770.12195122
2508 -403.29268293
2509  588.85365854
2510 -144.51219512
2511 -367.04878049
2512 -260.85365854
2513  209.43902439
2514  265.48780488
2515 -412.70731707
2516 -483.53658537
2517  137.68292683
2518 -209.39024390
2519 -114.90243902
2520  641.34146341
2521  111.24390244
2522 -118.26829268
2523 -629.43902439
2524 -123.78048780
2525  165.63414634
2526  176.46341463
2527  228.75609756
2528  280.70731707
2529  450.21951220
2530   24.31707317
2531 -625.53658537
2532  655.43902439
2533 -428.56097561
2534  697.34146341
2535  -95.29268293
2536 -529.58536585
2537  689.82926829
2538  351.48780488
2539  -60.41463415
2540 -565.24390244
2541 -473.68292683
2542  675.82926829
2543   39.14634146
2544  501.92682927
2545  605.92682927
2546  212.85365854
2547  -42.95121951
2548  339.29268293
2549 -558.51219512
2550  200.95121951
2551 -602.70731707
2552 -164.65853659
2553 -608.07317073
2554 -823.63414634
2555  454.36585366
2556 -233.09756098
2557  -22.90243902
2558 -438.80487805
2559   77.97560976
2560 -224.65853659
2561 -335.68292683
2562 -767.43902439
2563 -103.43902439
2564   69.39024390
2565 -405.58536585
2566 -113.73170732
2567  264.51219512
2568 -119.43902439
2569 -610.80487805
2570  -72.46341463
2571 -436.41463415
2572  385.73170732
2573   23.53658537
2574  -74.90243902
2575 -720.56097561
2576 -358.70731707
2577  328.75609756
2578  111.00000000
2579 -284.95121951
2580  319.68292683
2581  308.80487805
2582  241.82926829
2583   -0.12195122
2584  -11.73170732
2585   51.68292683
2586 -136.36585366
2587 -180.90243902
2588  118.17073171
2589  434.07317073
2590  660.02439024
2591  575.73170732
2592  137.39024390
2593  508.46341463
2594 -133.24390244
2595  290.90243902
2596   56.80487805
2597  -33.87804878
2598 -124.31707317
2599 -595.34146341
2600  766.51219512
2601 -571.34146341
2602  643.00000000
2603  656.21951220
2604  483.92682927
2605 -339.78048780
2606  -67.53658537
2607  -18.12195122
2608  109.09756098
2609   98.56097561
2610 -255.24390244
2611   50.75609756
2612  357.92682927
2613   94.51219512
2614  424.41463415
2615  -76.95121951
2616  147.14634146
2617   -4.75609756
2618  160.75609756
2619 -105.00000000
2620  -44.56097561
2621  430.65853659
2622 -239.53658537
2623 -179.39024390
2624  -48.70731707
2625  -32.07317073
2626  496.26829268
2627   66.70731707
2628  120.21951220
2629  561.04878049
2630  567.48780488
2631   24.07317073
2632   21.09756098
2633 -748.65853659
2634  -33.78048780
2635  166.02439024
2636  -92.95121951
2637 -205.09756098
2638  667.97560976
2639  752.31707317
2640 -770.07317073
2641  561.97560976
2642   76.56097561
2643    2.21951220
2644  -63.68292683
2645   21.48780488
2646  570.65853659
2647  617.68292683
2648 -151.73170732
2649 -194.07317073
2650  507.78048780
2651 -548.21951220
2652 -698.07317073
2653 -123.97560976
2654  162.95121951
2655 -260.95121951
2656  139.48780488
2657 -489.73170732
2658  579.24390244
2659   73.00000000
2660  184.65853659
2661 -120.51219512
2662 -709.92682927
2663 -544.75609756
2664  455.87804878
2665  -64.95121951
2666  737.87804878
2667  391.19512195
2668 -210.46341463
2669  -62.02439024
2670  -48.07317073
2671 -476.26829268
2672 -224.85365854
2673 -599.43902439
2674 -386.90243902
2675  -99.04878049
2676 -754.36585366
2677  458.21951220
2678   27.82926829
2679  673.53658537
2680   33.34146341
2681 -621.97560976
2682 -595.24390244
2683  127.97560976
2684  772.65853659
2685  -60.75609756
2686 -160.95121951
2687  -10.46341463
2688 -391.24390244
2689 -259.78048780
2690  350.85365854
2691 -436.95121951
2692 -259.68292683
2693 -239.73170732
2694 -232.80487805
2695  -68.51219512
2696  270.17073171
2697 -295.14634146
2698  161.68292683
2699 -416.90243902
2700  134.95121951
2701 -662.90243902
2702   30.60975610
2703   26.70731707
2704  275.58536585
2705  489.63414634
2706 -506.90243902
2707  619.78048780
2708  173.48780488
2709  323.39024390
2710  251.39024390
2711  -78.60975610
2712 -483.24390244
2713  363.82926829
2714  -63.58536585
2715   91.09756098
2716  158.70731707
2717  -89.24390244
2718  530.36585366
2719  -14.80487805
2720 -366.60975610
2721 -108.56097561
2722 -266.21951220
2723  188.17073171
2724 -404.95121951
2725 -185.68292683
2726 -198.36585366
2727  555.87804878
2728   34.65853659
2729 -141.09756098
2730  114.41463415
2731  324.21951220
2732  278.46341463
2733  464.90243902
2734 -550.26829268
2735 -538.26829268
2736  421.82926829
2737 -228.80487805
2738  -93.14634146
2739 -526.26829268
2740  225.63414634
2741  567.48780488
2742 -595.68292683
2743 -675.29268293
2744  409.58536585
2745 -609.73170732
2746 -691.43902439
2747 -618.60975610
2748  675.43902439
2749 -131.09756098
2750 -700.41463415
2751  201.58536585
2752 -730.51219512
2753 -169.73170732
2754 -155.14634146
2755 -155.09756098
2756 -356.95121951
2757  576.60975610
2758  115.87804878
2759  512.31707317
2760  -78.07317073
2761   90.02439024
2762  -22.90243902
2763 -670.21951220
2764 -535.29268293
2765 -608.12195122
2766  479.34146341
2767  -13.34146341
2768 -625.14634146
2769  459.29268293
2770  541.82926829
2771  393.53658537
2772  206.41463415
2773 -124.75609756
2774  177.29268293
2775  -40.17073171
2776 -116.75609756
2777  -62.12195122
2778  581.73170732
2779  421.24390244
2780  149.97560976
2781  311.87804878
2782  280.17073171
2783  374.41463415
2784 -111.78048780
2785  550.70731707
2786  661.43902439
2787 -317.97560976
2788 -392.56097561
2789 -647.58536585
2790  641.82926829
2791 -444.46341463
2792 -173.78048780
2793  529.68292683
2794 -417.29268293
2795  436.46341463
2796  519.97560976
2797   81.48780488
2798  -46.36585366
2799 -567.82926829
2800 -528.02439024
2801 -541.39024390
2802  343.63414634
2803   44.36585366
2804  -27.78048780
2805 -208.75609756
2806 -141.00000000
2807  278.31707317
2808  630.80487805
2809  510.90243902
2810   67.43902439
2811  249.73170732
2812 -446.36585366
2813  463.82926829
2814 -546.31707317
2815 -783.82926829
2816  601.68292683
2817  -37.09756098
2818 -696.75609756
2819  307.19512195
2820  -12.70731707
2821   46.85365854
2822   13.58536585
2823  -24.12195122
2824  -79.73170732
2825 -178.95121951
2826 -137.19512195
2827   92.36585366
2828 -110.75609756
2829  658.85365854
2830   71.87804878
2831 -413.73170732
2832  526.95121951
2833   85.78048780
2834 -536.31707317
2835   33.04878049
2836  527.09756098
2837 -188.26829268
2838  -49.34146341
2839  573.73170732
2840  477.63414634
2841 -116.80487805
2842  219.87804878
2843   -2.65853659
2844   49.19512195
2845  550.90243902
2846 -672.90243902
2847  606.21951220
2848  524.31707317
2849  456.80487805
2850  103.39024390
2851  -18.90243902
2852  423.82926829
2853 -557.09756098
2854 -480.02439024
2855  600.07317073
2856 -469.29268293
2857 -238.70731707
2858  298.51219512
2859 -753.63414634
2860   52.90243902
2861 -671.48780488
2862 -675.68292683
2863 -661.14634146
2864  111.43902439
2865 -184.07317073
2866  221.19512195
2867  495.48780488
2868  795.14634146
2869 -592.02439024
2870 -707.58536585
2871  454.51219512
2872  -42.41463415
2873 -246.80487805
2874  495.63414634
2875  606.60975610
2876 -643.39024390
2877  545.29268293
2878 -421.73170732
2879 -835.87804878
2880  504.12195122
2881  -32.95121951
2882  429.24390244
2883  516.07317073
2884 -439.43902439
2885  452.51219512
2886  -50.56097561
2887 -167.87804878
2888    7.09756098
2889 -227.09756098
2890 -603.04878049
2891 -194.80487805
2892  402.95121951
2893  491.58536585
2894  174.21951220
2895 -112.80487805
2896  164.31707317
2897   -5.78048780
2898  410.31707317
2899   55.34146341
2900  590.36585366
2901 -141.43902439
2902 -132.60975610
2903  421.92682927
2904 -119.63414634
2905 -357.04878049
2906 -387.48780488
2907  433.87804878
2908 -165.29268293
2909  400.70731707
2910 -137.82926829
2911  682.36585366
2912   68.95121951
2913  -35.34146341
2914  142.41463415
2915   16.70731707
2916   86.80487805
2917   60.60975610
2918 -722.12195122
2919 -672.26829268
2920  435.53658537
2921 -219.29268293
2922  517.04878049
2923 -223.87804878
2924 -685.82926829
2925   29.78048780
2926 -730.51219512
2927 -255.14634146
2928  537.00000000
2929  108.41463415
2930 -494.46341463
2931  -65.39024390
2932 -452.31707317
2933 -185.14634146
2934  508.80487805
2935 -563.87804878
2936 -130.85365854
2937 -631.82926829
2938   61.63414634
2939  665.19512195
2940  197.53658537
2941   21.63414634
2942  387.09756098
2943  602.26829268
2944 -193.87804878
2945   -3.78048780
2946  651.58536585
2947 -188.12195122
2948 -494.12195122
2949  -51.34146341
2950 -175.09756098
2951 -523.43902439
2952 -418.46341463
2953 -656.70731707
2954 -245.09756098
2955 -146.65853659
2956 -489.29268293
2957 -239.00000000
2958  782.46341463
2959 -134.17073171
2960   19.19512195
2961  376.75609756
2962 -647.43902439
2963 -272.60975610
2964  802.65853659
2965 -610.51219512
2966  505.87804878
2967 -102.46341463
2968  721.73170732
2969  718.26829268
2970  630.36585366
2971   -6.17073171
2972 -218.70731707
2973  116.85365854
2974 -505.14634146
2975  518.07317073
2976 -723.34146341
2977  -19.63414634
2978  560.41463415
2979 -707.82926829
2980 -738.90243902
2981 -522.21951220
2982 -737.14634146
2983  166.26829268
2984  291.34146341
2985 -286.95121951
2986 -522.85365854
2987  -82.36585366
2988 -637.14634146
2989   61.63414634
2990  206.12195122
2991 -328.56097561
2992 -454.41463415
2993  566.90243902
2994  -28.07317073
2995 -152.60975610
2996   31.78048780
2997  254.75609756
2998 -250.41463415
2999   40.26829268
3000 -513.87804878
3001  143.19512195
3002 -185.53658537
3003  203.48780488
3004   -9.92682927
3005  -74.95121951
3006 -596.21951220
3007  181.19512195
3008  582.56097561
3009  264.07317073
3010 -114.90243902
3011 -191.24390244
3012 -381.87804878
3013   33.29268293
3014 -707.29268293
3015   76.75609756
3016 -526.31707317
3017  102.26829268
3018 -521.39024390
3019  285.04878049
3020 -116.95121951
3021   74.56097561
3022  -53.68292683
3023 -246.95121951
3024  365.58536585
3025 -425.29268293
3026 -649.68292683
3027 -758.90243902
3028   32.85365854
3029  157.63414634
3030 -135.24390244
3031 -593.87804878
3032   37.00000000
3033  -12.07317073
3034   -9.14634146
3035  635.14634146
3036   81.58536585
3037  408.65853659
3038   56.07317073
3039  455.14634146
3040   14.75609756
3041  -31.00000000
3042 -398.31707317
3043 -152.31707317
3044  102.70731707
3045  347.43902439
3046 -383.97560976
3047 -123.78048780
3048 -660.07317073
3049  634.02439024
3050  356.65853659
3051  676.65853659
3052  758.07317073
3053 -554.70731707
3054 -742.51219512
3055 -678.65853659
3056  775.24390244
3057 -119.92682927
3058 -510.31707317
3059   61.14634146
3060 -400.51219512
3061 -464.02439024
3062  493.34146341
3063  152.02439024
3064 -170.07317073
3065 -102.51219512
3066 -260.85365854
3067   86.80487805
3068 -427.39024390
3069   39.92682927
3070 -543.58536585
3071 -501.58536585
3072   -8.65853659
3073 -761.97560976
3074  443.92682927
3075 -657.82926829
3076  342.80487805
3077  118.02439024
3078   37.24390244
3079 -210.17073171
3080  -15.58536585
3081 -348.21951220
3082   39.43902439
3083 -471.14634146
3084  665.00000000
3085  -20.36585366
3086  -85.09756098
3087  186.41463415
3088  -71.48780488
3089  -27.78048780
3090   67.48780488
3091 -673.58536585
3092  -19.39024390
3093  684.85365854
3094 -489.09756098
3095 -311.87804878
3096  -41.82926829
3097  416.75609756
3098 -513.78048780
3099 -111.04878049
3100 -573.63414634
3101 -623.53658537
3102 -165.48780488
3103  534.95121951
3104  -34.51219512
3105 -800.21951220
3106  686.51219512
3107 -192.70731707
3108 -174.60975610
3109 -481.58536585
3110 -391.63414634
3111 -426.60975610
3112  -82.31707317
3113  577.58536585
3114   99.04878049
3115  118.75609756
3116 -534.31707317
3117 -167.48780488
3118  339.78048780
3119 -113.53658537
3120 -673.92682927
3121 -821.82926829
3122   18.90243902
3123  137.34146341
3124   66.17073171
3125  787.19512195
3126  381.58536585
3127  516.26829268
3128  -84.41463415
3129   51.78048780
3130  583.78048780
3131  -89.43902439
3132  137.97560976
3133 -134.41463415
3134  -81.29268293
3135  179.09756098
3136  587.92682927
3137  -44.65853659
3138   10.02439024
3139  199.43902439
3140 -424.02439024
3141 -698.95121951
3142 -530.21951220
3143  706.02439024
3144  193.92682927
3145  371.19512195
3146 -122.12195122
3147 -505.14634146
3148  294.95121951
3149  622.60975610
3150  202.17073171
3151 -110.85365854
3152  419.04878049
3153  658.95121951
3154 -183.14634146
3155   59.58536585
3156  264.51219512
3157 -338.75609756
3158 -864.02439024
3159 -472.80487805
3160  190.51219512
3161 -531.92682927
3162 -190.95121951
3163  665.92682927
3164 -389.87804878
3165  155.04878049
3166 -330.75609756
3167    5.53658537
3168   77.73170732
3169 -467.39024390
3170  -32.90243902
3171  100.41463415
3172 -471.29268293
3173 -566.95121951
3174 -432.65853659
3175   61.58536585
3176  937.09756098
3177 -408.31707317
3178 -113.68292683
3179 -232.60975610
3180 -268.31707317
3181   42.95121951
3182   40.17073171
3183 -173.39024390
3184 -346.07317073
3185  193.68292683
3186  -21.19512195
3187 -292.21951220
3188  448.60975610
3189 -187.39024390
3190 -356.65853659
3191  467.82926829
3192 -202.02439024
3193    7.04878049
3194 -657.73170732
3195  586.51219512
3196   12.31707317
3197 -523.87804878
3198 -135.92682927
3199  753.53658537
3200   56.02439024
3201  555.39024390
3202  168.02439024
3203  743.87804878
3204  754.60975610
3205   -1.34146341
3206  115.04878049
3207 -759.87804878
3208  537.29268293
3209  519.29268293
3210  -64.02439024
3211 -583.63414634
3212 -151.09756098
3213  -70.85365854
3214   87.73170732
3215 -139.68292683
3216 -145.92682927
3217 -638.26829268
3218 -411.14634146
3219 -138.56097561
3220  467.43902439
3221  535.39024390
3222  148.41463415
3223 -578.60975610
3224 -433.24390244
3225  620.31707317
3226  -71.73170732
3227  -85.04878049
3228  391.14634146
3229  510.46341463
3230   46.80487805
3231  206.51219512
3232 -136.70731707
3233  318.36585366
3234  -36.51219512
3235 -114.60975610
3236 -502.02439024
3237 -453.78048780
3238  797.97560976
3239   15.53658537
3240 -610.65853659
3241 -490.56097561
3242  -29.43902439
3243 -685.09756098
3244  240.17073171
3245 -305.63414634
3246    1.14634146
3247 -367.92682927
3248  656.31707317
3249 -396.46341463
3250 -499.19512195
3251 -121.29268293
3252    4.60975610
3253  -93.73170732
3254 -412.41463415
3255   75.53658537
3256   83.14634146
3257 -169.58536585
3258 -270.80487805
3259  452.75609756
3260   -3.82926829
3261   87.48780488
3262  426.21951220
3263 -542.56097561
3264 -234.65853659
3265  -13.53658537
3266 -129.97560976
3267  -48.75609756
3268 -354.02439024
3269  388.26829268
3270 -596.70731707
3271  540.65853659
3272 -256.41463415
3273  512.12195122
3274   35.24390244
3275  -87.00000000
3276   72.26829268
3277 -509.53658537
3278  431.24390244
3279  754.70731707
3280 -442.41463415
3281 -111.43902439
3282  398.02439024
3283 -505.82926829
3284 -740.70731707
3285  307.78048780
3286  106.21951220
3287 -150.12195122
3288 -124.36585366
3289  103.19512195
3290 -559.73170732
3291  651.09756098
3292  567.53658537
3293 -151.68292683
3294 -540.17073171
3295  314.12195122
3296  462.07317073
3297 -567.48780488
3298 -172.31707317
3299   75.97560976
3300 -718.21951220
3301  656.60975610
3302  -54.95121951
3303 -718.41463415
3304 -104.12195122
3305 -106.51219512
3306  215.24390244
3307 -149.48780488
3308 -211.04878049
3309  -26.31707317
3310   60.85365854
3311    3.58536585
3312  106.07317073
3313  385.04878049
3314 -125.04878049
3315  200.60975610
3316  546.56097561
3317 -585.78048780
3318 -386.95121951
3319   85.04878049
3320   60.85365854
3321  399.09756098
3322  -50.56097561
3323 -546.46341463
3324  597.14634146
3325  376.02439024
3326 -544.31707317
3327  563.19512195
3328  301.19512195
3329   20.41463415
3330  703.00000000
3331 -166.65853659
3332  533.00000000
3333 -252.17073171
3334 -505.68292683
3335  -90.31707317
3336 -728.60975610
3337 -152.36585366
3338  567.68292683
3339  381.82926829
3340  471.43902439
3341  148.51219512
3342 -587.63414634
3343  161.14634146
3344 -456.31707317
3345 -207.04878049
3346  777.09756098
3347   34.07317073
3348 -141.78048780
3349  221.58536585
3350  -97.48780488
3351 -488.36585366
3352  720.80487805
3353 -297.19512195
3354  316.56097561
3355 -211.53658537
3356  103.97560976
3357   93.53658537
3358  304.56097561
3359  -33.82926829
3360  -51.92682927
3361  -51.29268293
3362 -779.78048780
3363 -502.21951220
3364   10.46341463
3365   95.19512195
3366   50.95121951
3367  -15.00000000
3368  783.34146341
3369 -569.24390244
3370  504.36585366
3371 -616.31707317
3372  769.68292683
3373 -615.04878049
3374  702.07317073
3375 -716.07317073
3376  458.46341463
3377  -69.87804878
3378   39.29268293
3379 -134.60975610
3380 -498.17073171
3381  -64.07317073
3382 -109.34146341
3383 -498.90243902
3384 -304.60975610
3385 -120.36585366
3386 -142.12195122
3387   43.78048780
3388  326.51219512
3389  -35.09756098
3390  663.29268293
3391   -0.02439024
3392  483.09756098
3393 -533.48780488
3394 -345.04878049
3395 -631.48780488
3396  -25.14634146
3397 -727.68292683
3398  -29.19512195
3399  120.56097561
3400  288.21951220
3401  -66.21951220
3402  107.82926829
3403 -540.02439024
3404  210.17073171
3405   -9.04878049
3406  -64.21951220
3407 -654.46341463
3408  466.95121951
3409 -216.70731707
3410  474.51219512
3411  147.29268293
3412 -406.60975610
3413  -12.90243902
3414 -135.92682927
3415 -438.56097561
3416  529.48780488
3417  424.70731707
3418  190.12195122
3419  733.68292683
3420  253.09756098
3421 -360.31707317
3422   -9.29268293
3423  667.04878049
3424 -356.26829268
3425   30.17073171
3426  697.82926829
3427  559.58536585
3428  266.85365854
3429 -165.87804878
3430 -545.48780488
3431 -650.02439024
3432 -185.58536585
3433   72.02439024
3434 -472.17073171
3435 -270.31707317
3436 -472.41463415
3437   71.78048780
3438  266.95121951
3439 -165.04878049
3440  587.24390244
3441  180.90243902
3442  401.34146341
3443 -331.39024390
3444 -103.43902439
3445   33.34146341
3446   19.82926829
3447  -47.04878049
3448    6.12195122
3449  583.63414634
3450 -557.39024390
3451  555.19512195
3452 -479.34146341
3453 -719.92682927
3454  162.21951220
3455 -714.41463415
3456  473.09756098
3457 -394.80487805
3458 -742.02439024
3459  223.58536585
3460  111.82926829
3461 -236.70731707
3462   98.70731707
3463  -84.95121951
3464 -431.82926829
3465 -658.46341463
3466   75.63414634
3467   66.90243902
3468  449.48780488
3469  633.14634146
3470 -610.07317073
3471  -46.31707317
3472 -655.97560976
3473    5.73170732
3474  -95.87804878
3475   36.51219512
3476 -197.73170732
3477  845.04878049
3478 -667.24390244
3479   80.26829268
3480  669.24390244
3481 -223.00000000
3482  600.65853659
3483  118.26829268
3484    9.14634146
3485  498.75609756
3486  352.36585366
3487 -373.04878049
3488 -293.48780488
3489  134.80487805
3490 -536.26829268
3491   84.65853659
3492  -73.09756098
3493   99.48780488
3494  404.21951220
3495  246.80487805
3496  171.58536585
3497   96.02439024
3498 -742.07317073
3499  247.39024390
3500   48.56097561
3501  379.00000000
3502 -598.56097561
3503 -109.19512195
3504  624.31707317
3505  199.14634146
3506  747.63414634
3507  321.87804878
3508  514.31707317
3509  -64.95121951
3510  -10.36585366
3511   30.85365854
3512 -203.43902439
3513 -128.17073171
3514  243.00000000
3515 -364.41463415
3516  123.58536585
3517  572.70731707
3518 -613.09756098
3519  -60.17073171
3520 -109.04878049
3521 -151.34146341
3522   95.92682927
3523  -85.97560976
3524 -488.41463415
3525 -346.26829268
3526 -102.65853659
3527 -382.31707317
3528  416.95121951
3529   77.63414634
3530 -410.90243902
3531 -727.39024390
3532   57.14634146
3533   45.29268293
3534 -709.58536585
3535  115.78048780
3536   -8.56097561
3537  623.97560976
3538  212.65853659
3539  127.53658537
3540  469.09756098
3541   53.73170732
3542 -570.12195122
3543  637.97560976
3544  336.36585366
3545 -537.82926829
3546  167.04878049
3547  819.63414634
3548 -689.58536585
3549 -561.53658537
3550  252.85365854
3551 -450.46341463
3552 -318.17073171
3553  173.09756098
3554  610.56097561
3555   96.70731707
3556  163.04878049
3557 -700.60975610
3558  713.58536585
3559    7.34146341
3560 -132.56097561
3561 -558.46341463
3562 -433.34146341
3563 -735.78048780
3564  -92.41463415
3565 -644.02439024
3566   28.80487805
3567   47.97560976
3568  -40.60975610
3569  -25.43902439
3570  212.51219512
3571  218.07317073
3572 -480.80487805
3573  673.14634146
3574 -582.56097561
3575  -52.85365854
3576 -307.48780488
3577  361.68292683
3578  145.78048780
3579  -63.04878049
3580   73.29268293
3581 -787.43902439
3582  107.04878049
3583 -746.36585366
3584 -113.82926829
3585  -79.04878049
3586  311.68292683
3587   65.24390244
3588 -121.68292683
3589 -636.21951220
3590 -126.85365854
3591  758.17073171
3592  -62.12195122
3593  686.70731707
3594  537.29268293
3595  691.00000000
3596 -429.39024390
3597  457.92682927
3598 -733.87804878
3599  313.39024390
3600  114.02439024
3601 -297.73170732
3602  -84.26829268
3603  -41.97560976
3604   80.95121951
3605 -105.43902439
3606  477.39024390
3607  155.14634146
3608  -20.02439024
3609 -657.39024390
3610   15.09756098
3611  210.21951220
3612 -116.60975610
3613  101.04878049
3614  515.97560976
3615  630.51219512
3616 -440.41463415
3617 -694.80487805
3618  156.31707317
3619 -210.75609756
3620 -679.58536585
3621   83.63414634
3622 -654.21951220
3623 -261.78048780
3624 -515.39024390
3625 -183.48780488
3626   40.65853659
3627  656.07317073
3628  -99.53658537
3629  560.56097561
3630 -101.19512195
3631  -47.87804878
3632 -686.65853659
3633 -319.92682927
3634 -165.24390244
3635 -168.95121951
3636  705.92682927
3637 -120.95121951
3638  675.48780488
3639  153.04878049
3640   75.53658537
3641 -192.90243902
3642 -697.97560976
3643  -59.09756098
3644  319.63414634
3645  536.75609756
3646 -217.68292683
3647  120.85365854
3648 -286.51219512
3649   91.43902439
3650  356.65853659
3651  554.85365854
3652 -287.82926829
3653  493.14634146
3654   -2.56097561
3655 -298.26829268
3656 -123.19512195
3657  281.78048780
3658  124.80487805
3659 -671.43902439
3660 -521.34146341
3661 -583.73170732
3662 -146.60975610
3663 -115.48780488
3664  575.43902439
3665  185.34146341
3666  286.26829268
3667  777.14634146
3668   29.29268293
3669  300.26829268
3670 -515.39024390
3671 -526.75609756
3672   41.78048780
3673 -116.80487805
3674 -777.68292683
3675  464.60975610
3676  623.00000000
3677  681.00000000
3678 -118.60975610
3679  703.73170732
3680  -53.43902439
3681  262.17073171
3682  718.21951220
3683  672.70731707
3684  381.19512195
3685  -68.51219512
3686  -46.31707317
3687 -112.46341463
3688 -405.73170732
3689  552.70731707
3690  194.02439024
3691  189.63414634
3692  510.12195122
3693  165.97560976
3694  153.53658537
3695  512.12195122
3696   -2.80487805
3697  544.65853659
3698 -499.63414634
3699  125.14634146
3700  556.60975610
3701  167.34146341
3702  314.46341463
3703 -109.82926829
3704  365.68292683
3705 -690.12195122
3706   42.90243902
3707 -121.09756098
3708  675.58536585
3709 -268.12195122
3710 -175.82926829
3711   54.02439024
3712   37.92682927
3713  168.07317073
3714  693.34146341
3715  556.46341463
3716 -612.07317073
3717  -56.80487805
3718   32.70731707
3719 -144.02439024
3720 -376.80487805
3721  442.41463415
3722   61.68292683
3723   33.58536585
3724  320.60975610
3725 -542.07317073
3726  579.29268293
3727 -420.46341463
3728    7.19512195
3729 -101.87804878
3730 -176.56097561
3731  -95.00000000
3732 -559.14634146
3733 -369.63414634
3734 -114.12195122
3735 -787.14634146
3736  812.75609756
3737 -656.85365854
3738 -238.31707317
3739  -46.07317073
3740 -202.36585366
3741   81.68292683
3742 -792.56097561
3743  112.41463415
3744  221.24390244
3745 -296.41463415
3746 -815.29268293
3747  179.92682927
3748 -347.09756098
3749  668.07317073
3750  512.51219512
3751 -103.09756098
3752  -98.80487805
3753 -192.70731707
3754  509.09756098
3755  -87.73170732
3756 -715.24390244
3757  197.78048780
3758   46.31707317
3759  396.46341463
3760  227.73170732
3761  370.21951220
3762 -475.39024390
3763 -202.90243902
3764 -191.19512195
3765  628.12195122
3766  538.51219512
3767 -715.58536585
3768 -184.90243902
3769 -543.14634146
3770 -110.60975610
3771  677.78048780
3772 -589.00000000
3773 -130.51219512
3774 -120.95121951
3775  314.31707317
3776 -621.29268293
3777    9.97560976
3778 -694.41463415
3779  -79.34146341
3780 -367.63414634
3781  193.04878049
3782  -63.68292683
3783    9.04878049
3784  507.58536585
3785 -304.90243902
3786 -579.19512195
3787  164.75609756
3788  293.34146341
3789 -773.39024390
3790 -181.09756098
3791  391.29268293
3792  292.51219512
3793 -152.80487805
3794  219.53658537
3795  330.17073171
3796   95.43902439
3797 -125.48780488
3798 -615.78048780
3799 -555.82926829
3800 -416.56097561
3801 -226.65853659
3802  558.21951220
3803 -370.17073171
3804  537.97560976
3805 -120.12195122
3806 -491.87804878
3807 -608.26829268
3808  -39.92682927
3809  580.36585366
3810   61.34146341
3811  205.48780488
3812  -23.34146341
3813 -499.34146341
3814  256.85365854
3815  598.36585366
3816 -119.43902439
3817  549.97560976
3818   85.24390244
3819  325.09756098
3820  103.97560976
3821  775.48780488
3822 -588.12195122
3823 -414.31707317
3824   22.26829268
3825  -40.36585366
3826  147.53658537
3827 -426.90243902
3828  204.17073171
3829  564.80487805
3830  -46.95121951
3831 -146.07317073
3832  493.92682927
3833    5.82926829
3834   14.26829268
3835  400.80487805
3836 -498.56097561
3837 -358.65853659
3838 -132.80487805
3839 -491.34146341
3840  639.73170732
3841  251.53658537
3842  -68.85365854
3843  335.48780488
3844 -618.21951220
3845   77.87804878
3846 -197.43902439
3847  134.31707317
3848  291.78048780
3849  125.43902439
3850 -292.70731707
3851  -85.63414634
3852 -719.19512195
3853  114.51219512
3854 -166.75609756
3855  416.21951220
3856   -2.46341463
3857  128.51219512
3858 -408.26829268
3859 -503.24390244
3860   96.12195122
3861 -128.95121951
3862  581.87804878
3863 -505.82926829
3864  -89.58536585
3865  456.70731707
3866 -456.80487805
3867  630.60975610
3868   21.04878049
3869  -94.95121951
3870 -348.90243902
3871  -27.24390244
3872  781.63414634
3873 -293.82926829
3874 -339.87804878
3875  247.48780488
3876  551.09756098
3877  -77.63414634
3878 -139.78048780
3879  344.65853659
3880 -229.53658537
3881 -572.60975610
3882  297.73170732
3883   68.56097561
3884   10.51219512
3885 -412.31707317
3886   -2.51219512
3887  392.07317073
3888  751.97560976
3889 -681.58536585
3890 -695.48780488
3891 -881.29268293
3892  601.09756098
3893 -588.70731707
3894 -779.68292683
3895  387.19512195
3896  -27.82926829
3897    9.73170732
3898 -512.90243902
3899  635.53658537
3900 -510.17073171
3901  241.00000000
3902  463.43902439
3903  -97.39024390
3904  551.24390244
3905  152.60975610
3906  459.63414634
3907  160.65853659
3908   69.82926829
3909  542.02439024
3910  -96.90243902
3911  314.46341463
3912 -176.65853659
3913 -352.80487805
3914   58.80487805
3915  399.04878049
3916 -711.48780488
3917  -46.80487805
3918 -191.39024390
3919 -688.12195122
3920  109.43902439
3921  577.39024390
3922  115.19512195
3923  775.19512195
3924 -499.92682927
3925 -742.12195122
3926   40.46341463
3927 -674.17073171
3928 -672.17073171
3929 -738.31707317
3930  301.24390244
3931  134.80487805
3932 -605.09756098
3933    4.85365854
3934   37.24390244
3935 -260.95121951
3936   31.00000000
3937   49.58536585
3938 -505.34146341
3939  467.53658537
3940  298.36585366
3941 -342.56097561
3942 -485.87804878
3943 -290.41463415
3944  -92.07317073
3945 -275.24390244
3946  486.36585366
3947 -777.24390244
3948  172.70731707
3949 -174.51219512
3950  592.85365854
3951 -391.58536585
3952  152.51219512
3953  641.34146341
3954  634.60975610
3955 -252.51219512
3956  567.09756098
3957  390.56097561
3958  399.68292683
3959 -662.85365854
3960  305.43902439
3961  659.68292683
3962  508.12195122
3963   32.95121951
3964 -772.41463415
3965 -513.63414634
3966 -579.53658537
3967 -641.29268293
3968 -501.68292683
3969  615.04878049
3970  603.00000000
3971 -601.97560976
3972 -267.43902439
3973   -6.12195122
3974   77.48780488
3975  158.95121951
3976 -120.02439024
3977  448.80487805
3978 -108.60975610
3979  229.14634146
3980 -405.04878049
3981 -519.43902439
3982  639.73170732
3983  491.00000000
3984 -704.02439024
3985   68.75609756
3986 -134.95121951
3987   87.92682927
3988 -659.58536585
3989 -219.58536585
3990  278.21951220
3991   41.34146341
3992  735.97560976
3993 -841.43902439
3994  552.07317073
3995   72.51219512
3996 -384.36585366
3997 -537.09756098
3998 -565.92682927
3999 -371.43902439
4000  697.29268293
4001  480.90243902
4002  287.34146341
4003 -188.75609756
4004  115.97560976
4005 -781.39024390
4006 -488.21951220
4007  613.82926829
4008 -670.56097561
4009 -500.46341463
4010  -80.26829268
4011  -82.31707317
4012 -298.90243902
4013 -354.17073171
4014  543.19512195
4015  481.00000000
4016 -171.24390244
4017 -385.39024390
4018  200.46341463
4019  360.31707317
4020  489.24390244
4021 -641.73170732
4022  359.39024390
4023  434.65853659
4024 -455.04878049
4025  193.24390244
4026 -313.43902439
4027 -192.85365854
4028  187.97560976
4029  123.82926829
4030  368.51219512
4031 -699.34146341
4032 -162.07317073
4033 -151.92682927
4034  165.53658537
4035 -633.48780488
4036  -15.68292683
4037   74.21951220
4038  -40.75609756
4039  126.31707317
4040  -93.68292683
4041  571.09756098
4042  -98.41463415
4043 -391.48780488
4044  185.04878049
4045  -31.29268293
4046 -272.75609756
4047  370.31707317
4048   82.17073171
4049 -212.12195122
4050 -599.87804878
4051  273.00000000
4052 -486.80487805
4053  707.39024390
4054  629.04878049
4055  672.60975610
4056 -413.24390244
4057 -175.63414634
4058   31.24390244
4059 -156.36585366
4060 -600.95121951
4061  170.95121951
4062  100.85365854
4063 -476.85365854
4064  679.48780488
4065  674.12195122
4066  394.95121951
4067  -80.60975610
4068  576.56097561
4069   41.00000000
4070 -162.26829268
4071  198.41463415
4072  258.56097561
4073  125.73170732
4074  -18.41463415
4075   43.97560976
4076 -674.60975610
4077  295.97560976
4078   61.09756098
4079   40.07317073
4080 -541.00000000
4081 -102.70731707
4082  307.82926829
4083 -621.63414634
4084 -205.82926829
4085   59.19512195
4086 -378.75609756
4087  351.82926829
4088 -125.19512195
4089  410.26829268
4090 -437.24390244
4091  100.51219512
4092  689.73170732
4093 -212.26829268
4094  -30.46341463
4095 -354.56097561
4096   55.43902439
4097  167.73170732
4098 -242.90243902
4099  173.87804878
4100  -90.36585366
4101  707.04878049
4102 -703.58536585
4103 -220.80487805
4104   74.65853659
4105 -278.26829268
4106  529.19512195
4107 -719.43902439
4108 -110.41463415
4109   19.48780488
4110  613.92682927
4111 -489.48780488
4112  536.41463415
4113   49.73170732
4114  706.80487805
4115  -30.65853659
4116  128.46341463
4117  751.48780488
4118  608.85365854
4119  209.24390244
4120 -600.51219512
4121 -578.26829268
4122 -580.95121951
4123  627.14634146
4124  -67.92682927
4125  234.26829268
4126 -496.31707317
4127  -88.51219512
4128   54.36585366
4129  110.65853659
4130  112.56097561
4131  506.31707317
4132  602.12195122
4133  661.63414634
4134 -271.43902439
4135   -6.95121951
4136  521.48780488
4137   22.36585366
4138 -562.26829268
4139  -24.80487805
4140  353.63414634
4141 -755.39024390
4142   44.85365854
4143  186.41463415
4144   32.95121951
4145  618.41463415
4146 -422.75609756
4147  537.68292683
4148  -72.75609756
4149  305.14634146
4150  -56.95121951
4151 -563.04878049
4152  526.07317073
4153 -279.87804878
4154 -552.85365854
4155  -57.34146341
4156 -489.39024390
4157 -124.75609756
4158  708.51219512
4159 -175.29268293
4160  440.60975610
4161 -180.41463415
4162  560.51219512
4163  442.75609756
4164  670.41463415
4165 -525.53658537
4166  209.39024390
4167 -326.02439024
4168 -152.65853659
4169  214.75609756
4170 -609.04878049
4171  -35.43902439
4172  -86.56097561
4173  431.53658537
4174 -453.00000000
4175  403.43902439
4176  592.85365854
4177 -292.17073171
4178 -484.90243902
4179  549.29268293
4180  118.17073171
4181   24.85365854
4182  150.70731707
4183 -158.70731707
4184  551.04878049
4185  -51.09756098
4186 -110.95121951
4187 -407.92682927
4188 -430.90243902
4189  206.31707317
4190  -28.80487805
4191  -60.07317073
4192  558.85365854
4193  586.41463415
4194 -569.78048780
4195 -351.58536585
4196 -234.80487805
4197  -96.17073171
4198 -598.21951220
4199  509.78048780
4200  187.29268293
4201 -127.00000000
4202 -380.60975610
4203 -464.12195122
4204  491.82926829
4205  535.29268293
4206  294.60975610
4207   21.43902439
4208  -67.92682927
4209  527.58536585
4210  -76.90243902
4211  543.73170732
4212 -226.26829268
4213  -96.41463415
4214 -229.53658537
4215  543.53658537
4216 -806.21951220
4217 -100.12195122
4218 -499.63414634
4219  542.56097561
4220  457.00000000
4221  685.09756098
4222  573.53658537
4223  189.87804878
4224 -297.00000000
4225  698.12195122
4226  602.95121951
4227  321.48780488
4228  200.80487805
4229  499.87804878
4230  391.24390244
4231 -404.12195122
4232 -657.78048780
4233 -590.65853659
4234  -96.75609756
4235 -544.90243902
4236 -532.85365854
4237  509.29268293
4238   78.80487805
4239 -508.26829268
4240  658.17073171
4241  652.21951220
4242  207.19512195
4243  -24.70731707
4244 -643.34146341
4245  505.00000000
4246 -245.09756098
4247  -76.46341463
4248 -525.73170732
4249   30.36585366
4250  176.90243902
4251 -566.46341463
4252  -12.56097561
4253 -161.04878049
4254  707.09756098
4255 -146.80487805
4256 -393.63414634
4257  472.46341463
4258  -75.19512195
4259  570.17073171
4260 -122.26829268
4261   74.70731707
4262   31.04878049
4263 -110.07317073
4264   35.24390244
4265  517.43902439
4266   83.09756098
4267 -129.68292683
4268 -156.70731707
4269  163.39024390
4270 -464.07317073
4271 -226.65853659
4272  -57.92682927
4273 -573.78048780
4274   39.92682927
4275  337.39024390
4276  715.97560976
4277  220.51219512
4278   87.00000000
4279 -704.85365854
4280 -272.51219512
4281 -218.31707317
4282  106.46341463
4283  193.68292683
4284 -258.31707317
4285   50.26829268
4286 -748.80487805
4287  485.58536585
4288 -201.19512195
4289  681.78048780
4290  162.46341463
4291 -674.95121951
4292  149.53658537
4293  481.39024390
4294 -686.12195122
4295  111.73170732
4296  633.63414634
4297 -627.78048780
4298  483.04878049
4299   78.12195122
4300 -721.04878049
4301  587.97560976
4302  124.17073171
4303  112.90243902
4304 -164.07317073
4305  108.75609756
4306 -267.53658537
4307  190.21951220
4308  837.63414634
4309 -750.70731707
4310 -596.31707317
4311 -450.41463415
4312  226.17073171
4313  339.04878049
4314  538.56097561
4315 -155.63414634
4316  101.78048780
4317  345.78048780
4318  515.63414634
4319 -692.36585366
4320 -616.31707317
4321  603.87804878
4322  235.87804878
4323  -71.14634146
4324  672.21951220
4325  -99.48780488
4326 -155.29268293
4327 -414.21951220
4328 -182.12195122
4329   17.34146341
4330 -591.43902439
4331  626.46341463
4332  490.90243902
4333   24.46341463
4334   58.17073171
4335  -45.29268293
4336   18.56097561
4337 -154.36585366
4338  564.51219512
4339 -470.65853659
4340   63.73170732
4341  720.21951220
4342  456.17073171
4343  -20.90243902
4344  -43.04878049
4345  -32.60975610
4346  391.29268293
4347  563.73170732
4348 -521.97560976
4349  -34.95121951
4350 -284.80487805
4351  433.14634146
4352  374.26829268
4353  153.58536585
4354  171.09756098
4355  588.31707317
4356  116.36585366
4357 -199.19512195
4358  -20.90243902
4359  -31.09756098
4360  306.21951220
4361  358.85365854
4362    8.46341463
4363 -840.65853659
4364 -390.90243902
4365  105.53658537
4366 -675.48780488
4367  141.00000000
4368  145.53658537
4369 -433.63414634
4370  693.34146341
4371 -220.17073171
4372 -499.87804878
4373 -684.60975610
4374   93.09756098
4375   98.80487805
4376 -113.43902439
4377  287.53658537
4378  -51.14634146
4379  408.51219512
4380  162.46341463
4381  541.34146341
4382   44.26829268
4383  -31.14634146
4384 -764.80487805
4385 -719.19512195
4386   24.65853659
4387  332.51219512
4388 -217.09756098
4389 -754.31707317
4390 -141.04878049
4391  392.07317073
4392   20.17073171
4393 -156.46341463
4394 -127.34146341
4395 -235.29268293
4396  204.65853659
4397   69.87804878
4398 -189.78048780
4399  490.46341463
4400  481.39024390
4401 -242.60975610
4402  869.58536585
4403 -585.63414634
4404  530.90243902
4405  757.24390244
4406  205.04878049
4407 -490.12195122
4408 -543.04878049
4409 -458.95121951
4410 -123.00000000
4411 -162.21951220
4412  509.29268293
4413  700.75609756
4414 -338.75609756
4415  139.04878049
4416  112.65853659
4417 -277.73170732
4418 -193.63414634
4419  146.70731707
4420  672.36585366
4421 -779.58536585
4422  -17.68292683
4423 -597.97560976
4424  446.41463415
4425 -833.73170732
4426 -442.07317073
4427   15.53658537
4428 -559.19512195
4429   49.48780488
4430  459.43902439
4431   29.34146341
4432 -460.36585366
4433  -42.07317073
4434 -389.34146341
4435  512.75609756
4436  271.58536585
4437  201.82926829
4438  320.07317073
4439  728.80487805
4440 -313.19512195
4441 -581.68292683
4442 -781.63414634
4443  -22.60975610
4444 -473.14634146
4445  -32.70731707
4446  567.00000000
4447  117.73170732
4448 -176.65853659
4449  -91.43902439
4450 -141.97560976
4451  615.00000000
4452  504.60975610
4453   73.29268293
4454  -71.24390244
4455  264.70731707
4456  425.34146341
4457    7.39024390
4458  407.19512195
4459 -111.39024390
4460 -142.21951220
4461   64.12195122
4462  249.73170732
4463  494.46341463
4464 -384.95121951
4465 -394.02439024
4466  552.17073171
4467  507.19512195
4468  604.85365854
4469  347.78048780
4470  668.36585366
4471  333.78048780
4472  753.78048780
4473    2.26829268
4474  -69.43902439
4475 -250.26829268
4476 -468.85365854
4477  255.19512195
4478   43.58536585
4479 -149.73170732
4480  363.82926829
4481 -479.78048780
4482 -855.68292683
4483 -472.95121951
4484   64.75609756
4485  472.90243902
4486 -390.95121951
4487 -559.19512195
4488    9.48780488
4489  650.21951220
4490  -27.73170732
4491 -679.68292683
4492 -234.26829268
4493  284.51219512
4494   74.95121951
4495  436.56097561
4496 -609.04878049
4497 -406.56097561
4498  368.21951220
4499  695.09756098
4500 -663.97560976
4501  535.34146341
4502  520.90243902
4503  731.39024390
4504 -589.29268293
4505  502.90243902
4506  131.24390244
4507 -207.14634146
4508 -405.48780488
4509  525.09756098
4510  684.85365854
4511  -29.82926829
4512 -714.21951220
4513 -454.02439024
4514   -3.24390244
4515  172.46341463
4516 -233.14634146
4517 -419.82926829
4518  147.48780488
4519 -146.21951220
4520  270.60975610
4521 -138.85365854
4522 -188.80487805
4523  352.70731707
4524  127.48780488
4525  660.80487805
4526 -531.73170732
4527 -109.04878049
4528  268.07317073
4529  113.92682927
4530  402.75609756
4531  247.78048780
4532  217.29268293
4533  172.26829268
4534  359.97560976
4535  495.82926829
4536 -159.78048780
4537 -247.14634146
4538 -138.85365854
4539 -191.14634146
4540  -11.29268293
4541 -508.17073171
4542  455.14634146
4543   18.07317073
4544  708.75609756
4545 -692.46341463
4546  -92.51219512
4547  643.24390244
4548   94.41463415
4549   57.53658537
4550  -56.90243902
4551 -193.63414634
4552  626.41463415
4553 -551.00000000
4554   -4.85365854
4555 -456.46341463
4556 -455.68292683
4557 -200.75609756
4558  383.53658537
4559  -55.34146341
4560  473.53658537
4561   41.19512195
4562  404.31707317
4563  -64.41463415
4564 -172.26829268
4565 -109.09756098
4566 -404.80487805
4567  644.60975610
4568 -155.63414634
4569 -104.36585366
4570   24.31707317
4571  -87.87804878
4572 -509.39024390
4573 -435.97560976
4574  125.63414634
4575   67.63414634
4576  146.80487805
4577 -597.04878049
4578  412.26829268
4579  177.24390244
4580 -189.68292683
4581  850.60975610
4582   39.78048780
4583  125.73170732
4584   99.00000000
4585  -16.02439024
4586 -128.31707317
4587 -385.34146341
4588  -54.46341463
4589 -238.46341463
4590 -101.58536585
4591 -216.26829268
4592    6.26829268
4593  -15.78048780
4594  179.14634146
4595  529.53658537
4596   61.78048780
4597  137.63414634
4598 -450.95121951
4599 -427.19512195
4600 -492.80487805
4601  -68.60975610
4602 -519.34146341
4603 -158.12195122
4604 -248.95121951
4605  464.85365854
4606 -524.85365854
4607  475.82926829
4608  486.07317073
4609  355.00000000
4610  -20.80487805
4611  414.85365854
4612  700.31707317
4613 -149.53658537
4614  -79.73170732
4615  671.53658537
4616   21.68292683
4617  651.78048780
4618 -261.09756098
4619 -341.34146341
4620 -499.53658537
4621 -493.04878049
4622  103.39024390
4623 -337.09756098
4624 -212.56097561
4625 -740.31707317
4626 -678.70731707
4627 -273.48780488
4628 -563.43902439
4629 -233.68292683
4630  364.17073171
4631 -206.60975610
4632  142.02439024
4633 -224.90243902
4634  489.82926829
4635 -329.97560976
4636 -349.92682927
4637    1.00000000
4638  187.87804878
4639  452.70731707
4640 -460.41463415
4641   92.31707317
4642  -31.82926829
4643  -65.24390244
4644 -427.68292683
4645  -11.39024390
4646   84.56097561
4647 -293.92682927
4648   97.58536585
4649  601.34146341
4650  141.92682927
4651 -595.43902439
4652   55.14634146
4653  252.26829268
4654  210.26829268
4655  465.48780488
4656 -462.95121951
4657   87.78048780
4658  183.14634146
4659 -450.07317073
4660  456.80487805
4661 -493.34146341
4662  130.41463415
4663  -30.51219512
4664  200.51219512
4665  698.46341463
4666 -471.19512195
4667  183.78048780
4668  -11.00000000
4669  193.04878049
4670  550.02439024
4671 -436.12195122
4672  -85.78048780
4673  -62.02439024
4674   42.26829268
4675   85.78048780
4676 -408.07317073
4677 -748.26829268
4678  638.51219512
4679 -477.43902439
4680  394.36585366
4681   72.02439024
4682  426.56097561
4683  455.09756098
4684  211.00000000
4685  -81.29268293
4686  377.82926829
4687  577.43902439
4688   52.65853659
4689 -190.26829268
4690 -627.24390244
4691 -102.51219512
4692 -530.95121951
4693    1.58536585
4694  361.68292683
4695 -596.02439024
4696   35.04878049
4697   56.12195122
4698 -353.48780488
4699  152.02439024
4700  129.43902439
4701 -601.87804878
4702    8.02439024
4703 -291.43902439
4704  513.48780488
4705  155.43902439
4706   62.26829268
4707 -324.95121951
4708   -0.90243902
4709  -49.43902439
4710  676.46341463
4711   33.82926829
4712 -418.90243902
4713   55.04878049
4714  406.65853659
4715 -230.46341463
4716  816.31707317
4717 -292.07317073
4718  749.58536585
4719  119.34146341
4720   16.31707317
4721 -446.41463415
4722 -512.07317073
4723  693.09756098
4724 -662.21951220
4725  215.34146341
4726  113.39024390
4727  538.21951220
4728  550.75609756
4729 -404.46341463
4730 -168.12195122
4731 -119.34146341
4732  379.39024390
4733  353.14634146
4734 -520.95121951
4735  538.07317073
4736 -665.29268293
4737 -488.60975610
4738   26.17073171
4739 -240.36585366
4740 -583.92682927
4741  172.56097561
4742   86.02439024
4743 -341.19512195
4744  -78.60975610
4745 -891.58536585
4746  269.48780488
4747  651.92682927
4748  -17.04878049
4749  357.19512195
4750  781.87804878
4751   -0.80487805
4752  109.68292683
4753 -772.12195122
4754  215.92682927
4755  874.26829268
4756 -219.87804878
4757  563.04878049
4758  606.36585366
4759  583.24390244
4760 -108.17073171
4761   45.39024390
4762  -47.43902439
4763 -307.09756098
4764  516.75609756
4765  278.21951220
4766 -404.12195122
4767 -105.34146341
4768 -205.92682927
4769   -3.58536585
4770  149.48780488
4771  119.14634146
4772  117.39024390
4773  505.68292683
4774  427.68292683
4775 -425.87804878
4776 -436.17073171
4777  -46.31707317
4778   -7.19512195
4779 -608.90243902
4780  144.46341463
4781   93.87804878
4782  560.60975610
4783   23.63414634
4784 -458.65853659
4785  769.00000000
4786  128.31707317
4787 -640.41463415
4788 -794.31707317
4789 -524.31707317
4790 -213.43902439
4791 -480.17073171
4792   72.41463415
4793 -352.21951220
4794  145.87804878
4795   56.95121951
4796   36.95121951
4797  546.12195122
4798  153.24390244
4799  623.34146341
4800  -55.29268293
4801  762.51219512
4802  335.58536585
4803 -294.41463415
4804  101.39024390
4805  264.70731707
4806 -449.48780488
4807   37.43902439
4808  605.43902439
4809 -394.26829268
4810 -373.29268293
4811 -676.02439024
4812 -387.14634146
4813  132.17073171
4814  244.85365854
4815 -301.19512195
4816  403.43902439
4817 -166.41463415
4818  -64.56097561
4819  156.26829268
4820  129.58536585
4821  273.73170732
4822  131.58536585
4823 -361.87804878
4824  437.68292683
4825  418.02439024
4826  363.43902439
4827  -60.70731707
4828   84.21951220
4829 -537.58536585
4830  -77.14634146
4831  230.07317073
4832 -176.17073171
4833  175.43902439
4834  150.02439024
4835  -65.63414634
4836    1.14634146
4837   70.90243902
4838  -72.17073171
4839  588.31707317
4840 -237.34146341
4841   36.02439024
4842 -204.12195122
4843 -238.07317073
4844  -13.14634146
4845  283.09756098
4846  149.14634146
4847  745.63414634
4848 -624.41463415
4849 -572.46341463
4850 -442.46341463
4851 -172.95121951
4852   57.19512195
4853  287.09756098
4854  264.70731707
4855   91.68292683
4856  675.24390244
4857  639.29268293
4858 -172.80487805
4859 -175.00000000
4860   58.26829268
4861  -49.04878049
4862   16.80487805
4863 -348.51219512
4864  402.41463415
4865  713.24390244
4866 -413.29268293
4867   57.09756098
4868 -559.87804878
4869    9.92682927
4870  481.63414634
4871  456.95121951
4872   78.07317073
4873 -241.39024390
4874 -250.02439024
4875  397.24390244
4876 -176.46341463
4877 -530.56097561
4878  -30.75609756
4879   -6.21951220
4880 -142.17073171
4881  550.17073171
4882  261.63414634
4883  -51.82926829
4884  266.90243902
4885  521.39024390
4886  422.80487805
4887   65.87804878
4888 -605.04878049
4889  513.63414634
4890  565.48780488
4891 -141.92682927
4892  138.46341463
4893  265.14634146
4894 -489.97560976
4895  362.85365854
4896 -452.90243902
4897 -673.58536585
4898  379.29268293
4899  -56.46341463
4900 -676.21951220
4901  400.31707317
4902  -72.12195122
4903  561.14634146
4904 -149.73170732
4905   69.43902439
4906  -18.65853659
4907 -411.14634146
4908 -103.34146341
4909 -274.75609756
4910  366.41463415
4911  125.73170732
4912  161.19512195
4913  246.41463415
4914 -525.82926829
4915 -156.26829268
4916 -607.68292683
4917  221.34146341
4918  -23.00000000
4919  531.63414634
4920 -100.46341463
4921 -648.95121951
4922 -374.41463415
4923  692.21951220
4924  -96.56097561
4925 -128.60975610
4926  -77.97560976
4927  404.80487805
4928   23.73170732
4929 -555.09756098
4930  -20.85365854
4931 -223.87804878
4932 -612.95121951
4933  -36.46341463
4934 -694.56097561
4935  640.51219512
4936 -228.85365854
4937  182.56097561
4938 -284.17073171
4939  320.21951220
4940  641.29268293
4941  233.04878049
4942   53.19512195
4943  -79.34146341
4944 -483.92682927
4945 -675.34146341
4946 -477.63414634
4947  -64.36585366
4948 -597.92682927
4949 -326.41463415
4950   69.04878049
4951 -710.21951220
4952 -548.31707317
4953  524.56097561
4954  605.87804878
4955 -432.26829268
4956 -148.02439024
4957   44.36585366
4958 -531.82926829
4959 -349.04878049
4960  345.78048780
4961   57.53658537
4962   30.90243902
4963    2.21951220
4964  -46.21951220
4965 -361.68292683
4966  534.36585366
4967 -235.68292683
4968 -578.26829268
4969    0.56097561
4970  692.80487805
4971   49.29268293
4972 -466.70731707
4973  489.29268293
4974  116.85365854
4975  758.12195122
4976 -428.02439024
4977   77.53658537
4978  227.82926829
4979  125.48780488
4980 -109.97560976
4981  146.12195122
4982  578.36585366
4983  132.41463415
4984  167.97560976
4985  -84.90243902
4986   89.78048780
4987 -824.90243902
4988  -10.70731707
4989  507.53658537
4990    5.39024390
4991  564.90243902
4992  657.82926829
4993  440.26829268
4994 -681.48780488
4995  473.63414634
4996  469.58536585
4997   30.80487805
4998  552.60975610
4999  397.78048780</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&lt;=</span> obs_mean, <span class="at">data =</span> null_dist_money)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
    0.444 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_money, <span class="sc">~</span> diffmean, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_mean, </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"purple"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Null Distribution by Permutation"</span>, </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Histogram"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Difference in Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><em>Conclusion:</em></h2>
<p>The line representing our observed difference in mean is located in the centre of the null distribution, this suggests that the our null hypothesis is not true. There is nothing special in the diff mean we got. We can reject the null hypothesis. There is not much difference in pocket money of males and females.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>